distractor(selan, barlan, harvests).
distractor(selan, talix, harvests).
distractor(brilan, xelan, harvests).
distractor(brilan, ullix, harvests).
distractor(kalan, yalan, harvests).
distractor(kalan, valix, harvests).
distractor(dulan, zelan, harvests).
distractor(dulan, wolix, harvests).
distractor(felan, barlan, harvests).
distractor(felan, xelix, harvests).
distractor(gilan, xelan, harvests).
distractor(gilan, yalix, harvests).
distractor(hellan, yalan, harvests).
distractor(hellan, zelix, harvests).
distractor(irlan, zelan, harvests).
distractor(irlan, barlix, harvests).
distractor(jolan, barlan, harvests).
distractor(jolan, talix, harvests).
distractor(klelan, xelan, harvests).
distractor(klelan, ullix, harvests).
