/* m218 (S2): content fuzz for the Windows write path. FsCreateFile, FsReplaceFile and FsCopyFile are given
   generated bytes (empty, one byte, LF only, CRLF only, mixed, lone CR, NUL bytes, 64 KiB, high bytes, no final
   newline). The file is read back with fopen "rb" and through FsReadFile; both must equal the bytes written.
   The root must hold no name but the files the test made and .fstxn.lock. Oracle only: no patch text, no
   AgentPatch, no crash. One runner, NTFS, cooperating writers. */
#ifdef _WIN32
#include "fs_write.h"
#include "fs_replace.h"
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <direct.h>
#define ROOT "test_fs_wincontent_scratch"
#define MAXB 65536
static uint32_t rs;
static uint32_t rnd(void){rs^=rs<<13;rs^=rs>>17;rs^=rs<<5;return rs;}
static int g_k,g_cls;static const char *g_op="setup";
static void ck(int ok,const char *label)
{if(!ok){fprintf(stderr,"FAIL %s (iteration %d, class %d, op %s, err %lu)\n",label,g_k,g_cls,g_op,GetLastError());exit(1);}}
/* One text token: a letter, or a line end chosen by the class. */
static size_t text(int c,unsigned char *b)
{size_t n=0,want=1+rnd()%200;
 while(n<want){unsigned r=rnd();
  if(r%7==0){
   if(c==3||(c==4&&((r>>8)&1)))b[n++]='\r';
   b[n++]='\n';}
  else b[n++]=(unsigned char)('a'+r%26);}
 if(c==9)b[n-1]=(unsigned char)'x';
 return n;}
static size_t gen(int c,unsigned char *b)
{size_t n,i;
 switch(c){
 case 0:return 0;
 case 1:b[0]=(unsigned char)rnd();return 1;
 case 2:case 3:case 4:case 9:return text(c,b);
 case 5:n=1+rnd()%100;for(i=0;i<n;i++)b[i]=(rnd()%5==0)?(unsigned char)'\r':(unsigned char)('a'+rnd()%26);return n;
 case 6:n=2+rnd()%300;for(i=0;i<n;i++)b[i]=(unsigned char)rnd();b[rnd()%n]=0;b[0]=0;return n;
 case 7:for(i=0;i<MAXB;i++)b[i]=(unsigned char)rnd();return MAXB;
 default:n=1+rnd()%300;for(i=0;i<n;i++)b[i]=(unsigned char)(0x80+rnd()%128);return n;}}
static void same(FS_READ_ROOT *root,const char *rel,const unsigned char *b,size_t n)
{char p[256];FILE *f;unsigned char *r,*api=NULL;size_t got,alen=0;FS_READ_META m;
 snprintf(p,sizeof p,ROOT "\\%s",rel);
 r=(unsigned char*)malloc(n+1);ck(r!=NULL,"malloc");
 f=fopen(p,"rb");ck(f!=NULL,"fopen readback");
 got=fread(r,1,n+1,f);ck(fclose(f)==0,"fclose");
 ck(got==n,"fopen size");ck(n==0||!memcmp(r,b,n),"fopen bytes");free(r);
 ck(FsReadFile(root,rel,&api,&alen,&m)==FS_READ_OK,"FsReadFile");
 ck(alen==n,"FsReadFile size");ck(n==0||!memcmp(api,b,n),"FsReadFile bytes");free(api);}
static int names(void)
{WIN32_FIND_DATAA d;HANDLE f=FindFirstFileA(ROOT "\\*",&d);int n=0;
 if(f==INVALID_HANDLE_VALUE)return 0;
 do{if(strcmp(d.cFileName,".")&&strcmp(d.cFileName,"..")&&strcmp(d.cFileName,".fstxn.lock"))n++;}while(FindNextFileA(f,&d));
 FindClose(f);return n;}
static void wipe(void)
{WIN32_FIND_DATAA d;HANDLE f=FindFirstFileA(ROOT "\\*",&d);char p[512];
 if(f!=INVALID_HANDLE_VALUE){do{if(strcmp(d.cFileName,".")&&strcmp(d.cFileName,"..")){
   snprintf(p,sizeof p,ROOT "\\%s",d.cFileName);SetFileAttributesA(p,FILE_ATTRIBUTE_NORMAL);DeleteFileA(p);}}while(FindNextFileA(f,&d));FindClose(f);}}
static unsigned run_seed(uint32_t seed,int iters)
{FS_READ_ROOT *root;unsigned char *a=malloc(MAXB+1),*b=malloc(MAXB+1);unsigned ok=0;
 ck(a&&b,"malloc");rs=seed?seed:1;
 wipe();_rmdir(ROOT);ck(_mkdir(ROOT)==0,"mkdir");
 ck(FsReadOpen(ROOT,&root)==FS_READ_OK,"open");
 for(g_k=0;g_k<iters;g_k++){
  size_t la,lb;int cb=(g_k*7+3)%10;
  g_cls=g_k%10;la=gen(g_cls,a);
  g_op="create";ck(FsCreateFile(root,"c",a,la,0644)==FS_READ_OK,"create");ok++;same(root,"c",a,la);
  g_cls=cb;lb=gen(cb,b);
  g_op="replace";ck(FsReplaceFile(root,"c",a,la,b,lb)==FS_READ_OK,"replace");ok++;same(root,"c",b,lb);
  g_op="copy";ck(FsCopyFile(root,"c","d",b,lb)==FS_READ_OK,"copy");ok++;same(root,"d",b,lb);
  g_op="names";ck(names()==2,"root names after one round");
  wipe();ck(names()==0,"wipe");
 }
 FsReadClose(root);wipe();_rmdir(ROOT);free(a);free(b);return ok;}
int main(void)
{static const uint32_t seeds[4]={1786707969u,1u,7u,12648430u};unsigned total=0;int i;
 for(i=0;i<4;i++){unsigned n=run_seed(seeds[i],100);printf("content fuzz seed=%u iterations=100 ops_ok=%u\n",(unsigned)seeds[i],n);fflush(stdout);total+=n;}
 printf("content fuzz done: seeds=4 iterations=400 ops_ok=%u\n",total);
 return total==1200?0:1;}
#else
int main(void){return 0;}
#endif
