expected(1, tra, stored, mirror, lima, reasoned).
expected(2, tra, stored, paddle, dublin, reasoned).
expected(3, tra, stored, radio, bern, reasoned).
expected(4, tra, stored, sextant, lisboa, reasoned).
expected(5, tra, stored, drum, atenea, reasoned).
expected(6, tra, stored, kettle, madrid, reasoned).
expected(7, tra, offers, moss, thyme, reasoned).
expected(8, tra, offers, nila, barley, reasoned).
expected(9, tra, offers, ovar, sage, reasoned).
expected(10, tra, offers, pela, beans, reasoned).
expected(11, core, reaches, alba, norway, retrieved).
expected(12, core, reaches, bruno, france, retrieved).
expected(13, core, reaches, carla, italy, retrieved).
expected(14, core, serves, diego, pork, retrieved).
expected(15, core, serves, elena, pepper, retrieved).
expected(16, core, visits, alba, roma, retrieved).
expected(17, core, visits, bruno, quito, retrieved).
expected(18, core, visits, carla, lima, retrieved).
expected(19, tra, tours, moss, bern, retrieved).
expected(20, tra, tours, nila, lisboa, retrieved).
expected(21, tra, tours, ovar, atenea, retrieved).
expected(22, core, unknown_person, zorin, -, unknown).
expected(23, core, unknown_person, velara, -, unknown).
