gold_fact(1, diego, serves, pork).
gold_fact(2, alba, reaches, peru).
gold_fact(3, jorge, reaches, ecuador).
gold_fact(4, carla, visits, roma).
gold_fact(5, carla, visits, roma).
gold_fact(6, carla, visits, lima).
gold_fact(7, carla, visits, lima).
gold_fact(8, carla, visits, bern).
gold_fact(9, carla, visits, bern).
gold_fact(10, carla, owns, violin).
gold_fact(11, carla, owns, violin).
gold_fact(12, violin, belongs_to, carla).
gold_fact(13, carla, owns, lantern).
gold_fact(14, carla, owns, lantern).
gold_fact(15, lantern, belongs_to, carla).
gold_fact(16, carla, cooks, gazpacho).
gold_fact(17, carla, cooks, gazpacho).
gold_fact(18, gazpacho, needs, garlic).
gold_fact(19, gazpacho, needs, garlic).
gold_none(20).
gold_fact(21, hugo, reaches, spain).
gold_fact(22, irene, reaches, grecia).
gold_fact(23, silo, tours, oslo).
gold_fact(24, silo, tours, oslo).
gold_fact(25, silo, tours, roma).
gold_fact(26, silo, tours, roma).
gold_fact(27, silo, tours, roma).
gold_fact(28, silo, tours, lima).
gold_fact(29, silo, tours, lima).
gold_fact(30, silo, keeps, mirror).
gold_fact(31, silo, keeps, mirror).
gold_fact(32, mirror, held_by, silo).
gold_fact(33, silo, keeps, sextant).
gold_fact(34, silo, keeps, sextant).
gold_fact(35, sextant, held_by, silo).
gold_fact(36, silo, prepares, broth).
gold_fact(37, silo, prepares, broth).
gold_fact(38, broth, requires, thyme).
gold_fact(39, broth, requires, thyme).
gold_fact(40, moss, tours, lima).
gold_fact(41, moss, tours, lima).
gold_fact(42, moss, tours, bern).
gold_fact(43, moss, tours, bern).
gold_fact(44, moss, tours, bern).
gold_fact(45, moss, tours, atenea).
gold_fact(46, moss, tours, atenea).
gold_fact(47, moss, keeps, mirror).
gold_fact(48, moss, keeps, mirror).
gold_fact(49, mirror, held_by, moss).
gold_fact(50, moss, keeps, sextant).
gold_fact(51, moss, keeps, sextant).
gold_fact(52, sextant, held_by, moss).
gold_fact(53, moss, prepares, broth).
gold_fact(54, moss, prepares, broth).
gold_fact(55, broth, requires, thyme).
gold_fact(56, broth, requires, thyme).
gold_none(57).
gold_fact(58, pela, tours, lisboa).
gold_fact(59, pela, tours, lisboa).
gold_fact(60, pela, tours, madrid).
gold_fact(61, pela, tours, madrid).
gold_fact(62, pela, tours, madrid).
gold_fact(63, pela, tours, paris).
gold_fact(64, pela, tours, paris).
gold_fact(65, pela, keeps, sextant).
gold_fact(66, pela, keeps, sextant).
gold_fact(67, sextant, held_by, pela).
gold_fact(68, pela, keeps, mirror).
gold_fact(69, pela, keeps, mirror).
gold_fact(70, mirror, held_by, pela).
gold_fact(71, pela, prepares, chowder).
gold_fact(72, pela, prepares, chowder).
gold_fact(73, chowder, requires, beans).
gold_fact(74, chowder, requires, beans).
gold_fact(75, hugo, visits, lisboa).
gold_fact(76, hugo, visits, lisboa).
gold_fact(77, hugo, visits, madrid).
gold_fact(78, hugo, visits, madrid).
gold_fact(79, hugo, visits, madrid).
gold_fact(80, hugo, visits, paris).
gold_fact(81, hugo, visits, paris).
gold_fact(82, hugo, owns, tablet).
gold_fact(83, hugo, owns, tablet).
gold_fact(84, tablet, belongs_to, hugo).
gold_fact(85, hugo, owns, compass).
gold_fact(86, hugo, owns, compass).
gold_fact(87, compass, belongs_to, hugo).
gold_fact(88, hugo, cooks, tortilla).
gold_fact(89, hugo, cooks, tortilla).
gold_fact(90, tortilla, needs, egg).
gold_fact(91, tortilla, needs, egg).
gold_fact(92, tove, tours, paris).
gold_fact(93, tove, tours, paris).
gold_fact(94, tove, tours, quito).
gold_fact(95, tove, tours, quito).
gold_fact(96, tove, tours, quito).
gold_fact(97, tove, tours, dublin).
gold_fact(98, tove, tours, dublin).
gold_fact(99, tove, keeps, paddle).
gold_fact(100, tove, keeps, paddle).
gold_fact(101, paddle, held_by, tove).
gold_fact(102, tove, keeps, drum).
gold_fact(103, tove, keeps, drum).
gold_fact(104, drum, held_by, tove).
gold_fact(105, tove, prepares, curry).
gold_fact(106, tove, prepares, curry).
gold_fact(107, curry, requires, barley).
gold_fact(108, curry, requires, barley).
gold_fact(109, hugo, reaches, portugal).
gold_fact(110, greta, reaches, norway).
gold_fact(111, alba, reaches, italy).
gold_fact(112, quim, tours, atenea).
gold_fact(113, quim, tours, atenea).
gold_fact(114, quim, tours, oslo).
gold_fact(115, quim, tours, oslo).
gold_fact(116, quim, tours, oslo).
gold_fact(117, quim, tours, roma).
gold_fact(118, quim, tours, roma).
gold_fact(119, quim, keeps, drum).
gold_fact(120, quim, keeps, drum).
gold_fact(121, drum, held_by, quim).
gold_fact(122, quim, keeps, paddle).
gold_fact(123, quim, keeps, paddle).
gold_fact(124, paddle, held_by, quim).
gold_fact(125, quim, prepares, tajine).
gold_fact(126, quim, prepares, tajine).
gold_fact(127, tajine, requires, lentils).
gold_fact(128, tajine, requires, lentils).
gold_none(129).
gold_fact(130, kira, reaches, peru).
gold_fact(131, carla, reaches, switzerland).
gold_fact(132, alba, serves, rice).
gold_fact(133, leo, serves, onion).
gold_fact(134, fabio, visits, dublin).
gold_fact(135, fabio, visits, dublin).
gold_fact(136, fabio, visits, lisboa).
gold_fact(137, fabio, visits, lisboa).
gold_fact(138, fabio, visits, madrid).
gold_fact(139, fabio, visits, madrid).
gold_fact(140, fabio, owns, lantern).
gold_fact(141, fabio, owns, lantern).
gold_fact(142, lantern, belongs_to, fabio).
gold_fact(143, fabio, owns, violin).
gold_fact(144, fabio, owns, violin).
gold_fact(145, violin, belongs_to, fabio).
gold_fact(146, fabio, cooks, migas).
gold_fact(147, fabio, cooks, migas).
gold_fact(148, migas, needs, onion).
gold_fact(149, migas, needs, onion).
gold_fact(150, carla, reaches, italy).
gold_none(151).
gold_none(152).
gold_none(153).
gold_fact(154, leo, reaches, france).
gold_none(155).
gold_fact(156, bruno, reaches, ecuador).
gold_fact(157, kira, visits, oslo).
gold_fact(158, kira, visits, oslo).
gold_fact(159, kira, visits, roma).
gold_fact(160, kira, visits, roma).
gold_fact(161, kira, visits, roma).
gold_fact(162, kira, visits, lima).
gold_fact(163, kira, visits, lima).
gold_fact(164, kira, owns, compass).
gold_fact(165, kira, owns, compass).
gold_fact(166, compass, belongs_to, kira).
gold_fact(167, kira, owns, tablet).
gold_fact(168, kira, owns, tablet).
gold_fact(169, tablet, belongs_to, kira).
gold_fact(170, kira, cooks, cocido).
gold_fact(171, kira, cooks, cocido).
gold_fact(172, cocido, needs, pepper).
gold_fact(173, cocido, needs, pepper).
gold_fact(174, leo, reaches, ecuador).
gold_none(175).
gold_fact(176, alba, visits, oslo).
gold_fact(177, alba, visits, oslo).
gold_fact(178, alba, visits, roma).
gold_fact(179, alba, visits, roma).
gold_fact(180, alba, visits, roma).
gold_fact(181, alba, visits, lima).
gold_fact(182, alba, visits, lima).
gold_fact(183, alba, owns, book).
gold_fact(184, alba, owns, book).
gold_fact(185, book, belongs_to, alba).
gold_fact(186, alba, owns, camera).
gold_fact(187, alba, owns, camera).
gold_fact(188, camera, belongs_to, alba).
gold_fact(189, alba, cooks, paella).
gold_fact(190, alba, cooks, paella).
gold_fact(191, paella, needs, rice).
gold_fact(192, paella, needs, rice).
gold_fact(193, nila, tours, dublin).
gold_fact(194, nila, tours, dublin).
gold_fact(195, nila, tours, lisboa).
gold_fact(196, nila, tours, lisboa).
gold_fact(197, nila, tours, lisboa).
gold_fact(198, nila, tours, madrid).
gold_fact(199, nila, tours, madrid).
gold_fact(200, nila, keeps, paddle).
gold_fact(201, nila, keeps, paddle).
gold_fact(202, paddle, held_by, nila).
gold_fact(203, nila, keeps, drum).
gold_fact(204, nila, keeps, drum).
gold_fact(205, drum, held_by, nila).
gold_fact(206, nila, prepares, curry).
gold_fact(207, nila, prepares, curry).
gold_fact(208, curry, requires, barley).
gold_fact(209, curry, requires, barley).
gold_fact(210, otto, reaches, ireland).
gold_fact(211, nora, serves, rice).
gold_fact(212, bruno, reaches, france).
gold_fact(213, diego, reaches, ecuador).
gold_none(214).
gold_fact(215, ovar, tours, bern).
gold_fact(216, ovar, tours, bern).
gold_fact(217, ovar, tours, atenea).
gold_fact(218, ovar, tours, atenea).
gold_fact(219, ovar, tours, atenea).
gold_fact(220, ovar, tours, oslo).
gold_fact(221, ovar, tours, oslo).
gold_fact(222, ovar, keeps, radio).
gold_fact(223, ovar, keeps, radio).
gold_fact(224, radio, held_by, ovar).
gold_fact(225, ovar, keeps, kettle).
gold_fact(226, ovar, keeps, kettle).
gold_fact(227, kettle, held_by, ovar).
gold_fact(228, ovar, prepares, goulash).
gold_fact(229, ovar, prepares, goulash).
gold_fact(230, goulash, requires, sage).
gold_fact(231, goulash, requires, sage).
gold_fact(232, irene, visits, atenea).
gold_fact(233, irene, visits, atenea).
gold_fact(234, irene, visits, oslo).
gold_fact(235, irene, visits, oslo).
gold_fact(236, irene, visits, roma).
gold_fact(237, irene, visits, roma).
gold_fact(238, irene, owns, violin).
gold_fact(239, irene, owns, violin).
gold_fact(240, violin, belongs_to, irene).
gold_fact(241, irene, owns, lantern).
gold_fact(242, irene, owns, lantern).
gold_fact(243, lantern, belongs_to, irene).
gold_fact(244, irene, cooks, gazpacho).
gold_fact(245, irene, cooks, gazpacho).
gold_fact(246, gazpacho, needs, garlic).
gold_fact(247, gazpacho, needs, garlic).
gold_fact(248, xana, tours, quito).
gold_fact(249, xana, tours, quito).
gold_fact(250, xana, tours, dublin).
gold_fact(251, xana, tours, dublin).
gold_fact(252, xana, tours, dublin).
gold_fact(253, xana, tours, lisboa).
gold_fact(254, xana, tours, lisboa).
gold_fact(255, xana, keeps, sextant).
gold_fact(256, xana, keeps, sextant).
gold_fact(257, sextant, held_by, xana).
gold_fact(258, xana, keeps, mirror).
gold_fact(259, xana, keeps, mirror).
gold_fact(260, mirror, held_by, xana).
gold_fact(261, xana, prepares, chowder).
gold_fact(262, xana, prepares, chowder).
gold_fact(263, chowder, requires, beans).
gold_fact(264, chowder, requires, beans).
gold_fact(265, greta, visits, bern).
gold_fact(266, greta, visits, bern).
gold_fact(267, greta, visits, atenea).
gold_fact(268, greta, visits, atenea).
gold_fact(269, greta, visits, oslo).
gold_fact(270, greta, visits, oslo).
gold_fact(271, greta, owns, book).
gold_fact(272, greta, owns, book).
gold_fact(273, book, belongs_to, greta).
gold_fact(274, greta, owns, camera).
gold_fact(275, greta, owns, camera).
gold_fact(276, camera, belongs_to, greta).
gold_fact(277, greta, cooks, paella).
gold_fact(278, greta, cooks, paella).
gold_fact(279, paella, needs, rice).
gold_fact(280, paella, needs, rice).
gold_fact(281, irene, reaches, norway).
gold_fact(282, nora, visits, roma).
gold_fact(283, nora, visits, roma).
gold_fact(284, nora, visits, lima).
gold_fact(285, nora, visits, lima).
gold_fact(286, nora, visits, lima).
gold_fact(287, nora, visits, bern).
gold_fact(288, nora, visits, bern).
gold_fact(289, nora, owns, book).
gold_fact(290, nora, owns, book).
gold_fact(291, book, belongs_to, nora).
gold_fact(292, nora, owns, camera).
gold_fact(293, nora, owns, camera).
gold_fact(294, camera, belongs_to, nora).
gold_fact(295, nora, cooks, paella).
gold_fact(296, nora, cooks, paella).
gold_fact(297, paella, needs, rice).
gold_fact(298, paella, needs, rice).
gold_fact(299, greta, serves, rice).
gold_fact(300, greta, reaches, switzerland).
gold_fact(301, elena, reaches, peru).
gold_none(302).
gold_fact(303, kira, reaches, italy).
gold_fact(304, alba, reaches, norway).
gold_fact(305, elena, reaches, switzerland).
gold_fact(306, nora, reaches, italy).
gold_fact(307, fabio, serves, onion).
gold_fact(308, kira, serves, pepper).
gold_fact(309, elena, serves, pepper).
gold_fact(310, irene, serves, garlic).
gold_none(311).
gold_fact(312, carla, reaches, peru).
gold_fact(313, otto, reaches, portugal).
gold_fact(314, nora, reaches, switzerland).
gold_fact(315, nora, reaches, peru).
gold_fact(316, jorge, reaches, france).
gold_fact(317, kira, reaches, norway).
gold_fact(318, bruno, reaches, ireland).
gold_fact(319, jorge, visits, madrid).
gold_fact(320, jorge, visits, madrid).
gold_fact(321, jorge, visits, paris).
gold_fact(322, jorge, visits, paris).
gold_fact(323, jorge, visits, quito).
gold_fact(324, jorge, visits, quito).
gold_fact(325, jorge, owns, camera).
gold_fact(326, jorge, owns, camera).
gold_fact(327, camera, belongs_to, jorge).
gold_fact(328, jorge, owns, book).
gold_fact(329, jorge, owns, book).
gold_fact(330, book, belongs_to, jorge).
gold_fact(331, jorge, cooks, fabada).
gold_fact(332, jorge, cooks, fabada).
gold_fact(333, fabada, needs, pork).
gold_fact(334, fabada, needs, pork).
gold_fact(335, otto, reaches, ecuador).
gold_fact(336, leo, reaches, ireland).
gold_none(337).
gold_fact(338, fabio, reaches, ireland).
gold_fact(339, jorge, serves, pork).
gold_none(340).
gold_none(341).
gold_fact(342, otto, serves, egg).
gold_fact(343, greta, reaches, grecia).
gold_fact(344, bruno, serves, egg).
gold_none(345).
gold_fact(346, diego, reaches, ireland).
gold_fact(347, bruno, visits, paris).
gold_fact(348, bruno, visits, paris).
gold_fact(349, bruno, visits, quito).
gold_fact(350, bruno, visits, quito).
gold_fact(351, bruno, visits, dublin).
gold_fact(352, bruno, visits, dublin).
gold_fact(353, bruno, owns, tablet).
gold_fact(354, bruno, owns, tablet).
gold_fact(355, tablet, belongs_to, bruno).
gold_fact(356, bruno, owns, compass).
gold_fact(357, bruno, owns, compass).
gold_fact(358, compass, belongs_to, bruno).
gold_fact(359, bruno, cooks, tortilla).
gold_fact(360, bruno, cooks, tortilla).
gold_fact(361, tortilla, needs, egg).
gold_fact(362, tortilla, needs, egg).
gold_fact(363, otto, visits, quito).
gold_fact(364, otto, visits, quito).
gold_fact(365, otto, visits, dublin).
gold_fact(366, otto, visits, dublin).
gold_fact(367, otto, visits, dublin).
gold_fact(368, otto, visits, lisboa).
gold_fact(369, otto, visits, lisboa).
gold_fact(370, otto, owns, tablet).
gold_fact(371, otto, owns, tablet).
gold_fact(372, tablet, belongs_to, otto).
gold_fact(373, otto, owns, compass).
gold_fact(374, otto, owns, compass).
gold_fact(375, compass, belongs_to, otto).
gold_fact(376, otto, cooks, tortilla).
gold_fact(377, otto, cooks, tortilla).
gold_fact(378, tortilla, needs, egg).
gold_fact(379, tortilla, needs, egg).
gold_fact(380, elena, reaches, grecia).
gold_none(381).
gold_fact(382, jorge, reaches, spain).
gold_none(383).
gold_fact(384, fabio, reaches, portugal).
gold_none(385).
gold_fact(386, hugo, reaches, france).
gold_fact(387, carla, serves, garlic).
gold_none(388).
gold_fact(389, diego, reaches, portugal).
gold_fact(390, diego, visits, quito).
gold_fact(391, diego, visits, quito).
gold_fact(392, diego, visits, dublin).
gold_fact(393, diego, visits, dublin).
gold_fact(394, diego, visits, lisboa).
gold_fact(395, diego, visits, lisboa).
gold_fact(396, diego, owns, camera).
gold_fact(397, diego, owns, camera).
gold_fact(398, camera, belongs_to, diego).
gold_fact(399, diego, owns, book).
gold_fact(400, diego, owns, book).
gold_fact(401, book, belongs_to, diego).
gold_fact(402, diego, cooks, fabada).
gold_fact(403, diego, cooks, fabada).
gold_fact(404, fabada, needs, pork).
gold_fact(405, fabada, needs, pork).
gold_fact(406, hugo, serves, egg).
gold_none(407).
gold_fact(408, madrid, in, spain).
gold_fact(409, madrid, in, spain).
gold_fact(410, oslo, in, norway).
gold_fact(411, oslo, in, norway).
gold_fact(412, paris, in, france).
gold_fact(413, paris, in, france).
gold_fact(414, roma, in, italy).
gold_fact(415, roma, in, italy).
gold_fact(416, quito, in, ecuador).
gold_fact(417, quito, in, ecuador).
gold_fact(418, lima, in, peru).
gold_fact(419, lima, in, peru).
gold_fact(420, dublin, in, ireland).
gold_fact(421, dublin, in, ireland).
gold_fact(422, bern, in, switzerland).
gold_fact(423, bern, in, switzerland).
gold_fact(424, lisboa, in, portugal).
gold_fact(425, lisboa, in, portugal).
gold_fact(426, atenea, in, grecia).
gold_fact(427, atenea, in, grecia).
gold_fact(428, urre, tours, roma).
gold_fact(429, urre, tours, roma).
gold_fact(430, urre, tours, lima).
gold_fact(431, urre, tours, lima).
gold_fact(432, urre, tours, lima).
gold_fact(433, urre, tours, bern).
gold_fact(434, urre, tours, bern).
gold_fact(435, urre, keeps, radio).
gold_fact(436, urre, keeps, radio).
gold_fact(437, radio, held_by, urre).
gold_fact(438, urre, keeps, kettle).
gold_fact(439, urre, keeps, kettle).
gold_fact(440, kettle, held_by, urre).
gold_fact(441, urre, prepares, goulash).
gold_fact(442, urre, prepares, goulash).
gold_fact(443, goulash, requires, sage).
gold_fact(444, goulash, requires, sage).
gold_fact(445, leo, visits, paris).
gold_fact(446, leo, visits, paris).
gold_fact(447, leo, visits, quito).
gold_fact(448, leo, visits, quito).
gold_fact(449, leo, visits, dublin).
gold_fact(450, leo, visits, dublin).
gold_fact(451, leo, owns, lantern).
gold_fact(452, leo, owns, lantern).
gold_fact(453, lantern, belongs_to, leo).
gold_fact(454, leo, owns, violin).
gold_fact(455, leo, owns, violin).
gold_fact(456, violin, belongs_to, leo).
gold_fact(457, leo, cooks, migas).
gold_fact(458, leo, cooks, migas).
gold_fact(459, migas, needs, onion).
gold_fact(460, migas, needs, onion).
gold_fact(461, elena, visits, lima).
gold_fact(462, elena, visits, lima).
gold_fact(463, elena, visits, bern).
gold_fact(464, elena, visits, bern).
gold_fact(465, elena, visits, atenea).
gold_fact(466, elena, visits, atenea).
gold_fact(467, elena, owns, compass).
gold_fact(468, elena, owns, compass).
gold_fact(469, compass, belongs_to, elena).
gold_fact(470, elena, owns, tablet).
gold_fact(471, elena, owns, tablet).
gold_fact(472, tablet, belongs_to, elena).
gold_fact(473, elena, cooks, cocido).
gold_fact(474, elena, cooks, cocido).
gold_fact(475, cocido, needs, pepper).
gold_fact(476, cocido, needs, pepper).
gold_fact(477, fabio, reaches, spain).
gold_fact(478, rufa, tours, madrid).
gold_fact(479, rufa, tours, madrid).
gold_fact(480, rufa, tours, paris).
gold_fact(481, rufa, tours, paris).
gold_fact(482, rufa, tours, paris).
gold_fact(483, rufa, tours, quito).
gold_fact(484, rufa, tours, quito).
gold_fact(485, rufa, keeps, kettle).
gold_fact(486, rufa, keeps, kettle).
gold_fact(487, kettle, held_by, rufa).
gold_fact(488, rufa, keeps, radio).
gold_fact(489, rufa, keeps, radio).
gold_fact(490, radio, held_by, rufa).
gold_fact(491, rufa, prepares, stew).
gold_fact(492, rufa, prepares, stew).
gold_fact(493, stew, requires, cumin).
gold_fact(494, stew, requires, cumin).
gold_fact(495, irene, reaches, italy).
