heldout(mirror, lima, stored).
heldout(paddle, dublin, stored).
heldout(radio, bern, stored).
heldout(sextant, lisboa, stored).
heldout(drum, atenea, stored).
heldout(kettle, madrid, stored).
heldout(moss, thyme, offers).
heldout(nila, barley, offers).
heldout(ovar, sage, offers).
heldout(pela, beans, offers).
