distractor(anna, switzerland, reaches).
distractor(bririn, switzerland, reaches).
distractor(klerin, switzerland, reaches).
distractor(otrin, norway, reaches).
distractor(selrin, switzerland, reaches).
distractor(quivio, switzerland, arrives).
distractor(yavio, switzerland, arrives).
distractor(brisel, switzerland, arrives).
distractor(gisel, norway, arrives).
distractor(klesel, switzerland, arrives).
distractor(quidor, ullix, borrows).
distractor(yador, ullix, borrows).
distractor(brikan, ullix, borrows).
distractor(gikan, quilix, borrows).
distractor(klekan, ullix, borrows).
