memfact(luis,work,paris,1.0,1).
memfact(maria,work,london,1.0,1).
memfact(juan,work,madrid,1.0,1).
memfact(juan,live,madrid,1.0,1).
memfact(juan,visit,paris,1.0,1).
memfact(juan,speak,spanish,1.0,1).
memfact(maria,live,paris,1.0,1).
memfact(maria,own,cat,1.0,1).
memfact(luis,visit,london,1.0,1).
memfact(luis,own,car,1.0,1).
memfact(ana,live,rome,1.0,1).
memfact(ana,visit,madrid,1.0,1).
memfact(ana,speak,french,1.0,1).
memfact(pedro,work,rome,1.0,1).
memfact(pedro,visit,madrid,1.0,1).