% probe_nl.pl — sondas de dialogo natural sobre alice_clean.
:- encoding(utf8).
:- consult('chat.pl').

probe :-
    bb_load('alice_clean.knowledge.pl'),
    writeln('---1 who found key?---'),
    chat_line("who found key?"),
    writeln('---2 what did she find?---'),
    chat_line("what did she find?"),
    writeln('---3 who ate cake?---'),
    chat_line("who ate cake?"),
    writeln('---4 did she eat cake?---'),
    chat_line("did she eat cake?"),
    writeln('---5 what did she eat?---'),
    chat_line("what did she eat?"),
    writeln('---6 she followed the white rabbit?---'),
    chat_line("she followed the white rabbit?"),
    writeln('---7 what did alice find?---'),
    chat_line("what did alice find?"),
    writeln('---8 who found the key?---'),
    chat_line("who found the key?"),
    writeln('---9 And the cake?---'),
    chat_line("And the cake?"),
    writeln('---10 what did she drink?---'),
    chat_line("what did she drink?"),
    writeln('---11 did alice find a key?---'),
    chat_line("did alice find a key?"),
    writeln('---12 why did she find the key?---'),
    chat_line("why did she find the key?"),
    writeln('---13 who did she meet?---'),
    chat_line("who did she meet?"),
    writeln('---14 more---'),
    chat_line("more"),
    writeln('---15 she waved a fan---'),
    chat_line("she waved a fan"),
    writeln('---16 what about the queen?---'),
    chat_line("what about the queen?"),
    writeln('---17 did she threaten alice?---'),
    chat_line("did she threaten alice?"),
    halt.
