expected(1, core, reach, alba, norway, reasoned).
expected(2, core, reach, bruno, ecuador, reasoned).
expected(3, core, reach, carla, switzerland, reasoned).
expected(4, core, reach, diego, ecuador, reasoned).
expected(5, core, reach, elena, switzerland, reasoned).
expected(6, core, reach, fabio, spain, reasoned).
expected(7, core, reach, greta, switzerland, reasoned).
expected(8, core, reach, hugo, spain, reasoned).
expected(9, core, reach, irene, italy, reasoned).
expected(10, core, reach, jorge, spain, reasoned).
expected(11, tra, reach, quinn, ireland, reasoned).
expected(12, tra, reach, rosa, switzerland, reasoned).
expected(13, tra, reach, sven, portugal, reasoned).
expected(14, core, based, carla, switzerland, reasoned).
expected(15, core, based, diego, spain, reasoned).
expected(16, core, based, elena, italy, reasoned).
expected(17, core, based, fabio, ireland, reasoned).
expected(18, core, based, greta, grecia, reasoned).
expected(19, core, based, hugo, france, reasoned).
expected(20, tra, based, tara, grecia, reasoned).
expected(21, tra, based, ugo, france, reasoned).
expected(22, core, visits, alba, oslo, retrieved).
expected(23, core, visits, bruno, paris, retrieved).
expected(24, core, visits, carla, roma, retrieved).
expected(25, core, visits, diego, quito, retrieved).
expected(26, core, visits, elena, lima, retrieved).
expected(27, core, visits, fabio, dublin, retrieved).
expected(28, tra, visits, quinn, lisboa, retrieved).
expected(29, tra, visits, rosa, atenea, retrieved).
expected(30, tra, visits, sven, madrid, retrieved).
expected(31, core, owns, alba, book, retrieved).
expected(32, core, owns, bruno, tablet, retrieved).
expected(33, core, owns, carla, violin, retrieved).
expected(34, core, owns, diego, camera, retrieved).
expected(35, tra, owns, quinn, globe, retrieved).
expected(36, tra, owns, rosa, kettle, retrieved).
expected(37, core, unknown_person, zorin, -).
expected(38, core, unknown_person, velara, -).
