gold_none(1).
gold_fact(2, pablo, reaches, portugal).
gold_fact(3, tara, reaches, italy).
gold_fact(4, marta, based, italy).
gold_fact(5, tara, reaches, norway).
gold_fact(6, quinn, reaches, spain).
gold_fact(7, diego, reaches, ireland).
gold_none(8).
gold_fact(9, pablo, visits, dublin).
gold_fact(10, pablo, visits, dublin).
gold_fact(11, pablo, visits, dublin).
gold_fact(12, pablo, visits, lisboa).
gold_fact(13, pablo, visits, lisboa).
gold_fact(14, pablo, visits, lisboa).
gold_fact(15, pablo, visits, madrid).
gold_fact(16, pablo, visits, madrid).
gold_fact(17, pablo, visits, madrid).
gold_fact(18, pablo, owns, lantern).
gold_fact(19, pablo, owns, lantern).
gold_fact(20, lantern, belongs_to, pablo).
gold_fact(21, pablo, owns, paddle).
gold_fact(22, pablo, owns, paddle).
gold_fact(23, pablo, owns, paddle).
gold_fact(24, paddle, belongs_to, pablo).
gold_fact(25, pablo, works_at, helvetia).
gold_fact(26, pablo, works_at, helvetia).
gold_fact(27, diego, visits, quito).
gold_fact(28, diego, visits, quito).
gold_fact(29, diego, visits, quito).
gold_fact(30, diego, visits, dublin).
gold_fact(31, diego, visits, dublin).
gold_fact(32, diego, visits, dublin).
gold_fact(33, diego, visits, lisboa).
gold_fact(34, diego, visits, lisboa).
gold_fact(35, diego, visits, lisboa).
gold_fact(36, diego, owns, camera).
gold_fact(37, diego, owns, camera).
gold_fact(38, camera, belongs_to, diego).
gold_fact(39, diego, owns, kettle).
gold_fact(40, diego, owns, kettle).
gold_fact(41, diego, owns, kettle).
gold_fact(42, kettle, belongs_to, diego).
gold_fact(43, diego, works_at, danubio).
gold_fact(44, diego, works_at, danubio).
gold_fact(45, rosa, reaches, norway).
gold_none(46).
gold_fact(47, marta, visits, roma).
gold_fact(48, marta, visits, roma).
gold_fact(49, marta, visits, roma).
gold_fact(50, marta, visits, lima).
gold_fact(51, marta, visits, lima).
gold_fact(52, marta, visits, lima).
gold_fact(53, marta, visits, bern).
gold_fact(54, marta, visits, bern).
gold_fact(55, marta, visits, bern).
gold_fact(56, marta, owns, violin).
gold_fact(57, marta, owns, violin).
gold_fact(58, violin, belongs_to, marta).
gold_fact(59, marta, owns, globe).
gold_fact(60, marta, owns, globe).
gold_fact(61, marta, owns, globe).
gold_fact(62, globe, belongs_to, marta).
gold_fact(63, marta, works_at, electra).
gold_fact(64, marta, works_at, electra).
gold_fact(65, fabio, reaches, portugal).
gold_fact(66, irene, reaches, grecia).
gold_fact(67, alba, reaches, peru).
gold_fact(68, fabio, visits, dublin).
gold_fact(69, fabio, visits, dublin).
gold_fact(70, fabio, visits, dublin).
gold_fact(71, fabio, visits, lisboa).
gold_fact(72, fabio, visits, lisboa).
gold_fact(73, fabio, visits, lisboa).
gold_fact(74, fabio, visits, madrid).
gold_fact(75, fabio, visits, madrid).
gold_fact(76, fabio, visits, madrid).
gold_fact(77, fabio, owns, lantern).
gold_fact(78, fabio, owns, lantern).
gold_fact(79, lantern, belongs_to, fabio).
gold_fact(80, fabio, owns, paddle).
gold_fact(81, fabio, owns, paddle).
gold_fact(82, fabio, owns, paddle).
gold_fact(83, paddle, belongs_to, fabio).
gold_fact(84, fabio, works_at, futura).
gold_fact(85, fabio, works_at, futura).
gold_fact(86, quinn, visits, dublin).
gold_fact(87, quinn, visits, dublin).
gold_fact(88, quinn, visits, dublin).
gold_fact(89, quinn, visits, lisboa).
gold_fact(90, quinn, visits, lisboa).
gold_fact(91, quinn, visits, lisboa).
gold_fact(92, quinn, visits, madrid).
gold_fact(93, quinn, visits, madrid).
gold_fact(94, quinn, visits, madrid).
gold_fact(95, quinn, owns, globe).
gold_fact(96, quinn, owns, globe).
gold_fact(97, globe, belongs_to, quinn).
gold_fact(98, quinn, owns, book).
gold_fact(99, quinn, owns, book).
gold_fact(100, quinn, owns, book).
gold_fact(101, book, belongs_to, quinn).
gold_fact(102, quinn, works_at, danubio).
gold_fact(103, quinn, works_at, danubio).
gold_fact(104, olga, reaches, peru).
gold_fact(105, nils, based, ireland).
gold_fact(106, jorge, visits, madrid).
gold_fact(107, jorge, visits, madrid).
gold_fact(108, jorge, visits, madrid).
gold_fact(109, jorge, visits, paris).
gold_fact(110, jorge, visits, paris).
gold_fact(111, jorge, visits, paris).
gold_fact(112, jorge, visits, quito).
gold_fact(113, jorge, visits, quito).
gold_fact(114, jorge, visits, quito).
gold_fact(115, jorge, owns, paddle).
gold_fact(116, jorge, owns, paddle).
gold_fact(117, paddle, belongs_to, jorge).
gold_fact(118, jorge, owns, camera).
gold_fact(119, jorge, owns, camera).
gold_fact(120, jorge, owns, camera).
gold_fact(121, camera, belongs_to, jorge).
gold_fact(122, jorge, works_at, borealis).
gold_fact(123, jorge, works_at, borealis).
gold_none(124).
gold_fact(125, hugo, reaches, portugal).
gold_fact(126, pablo, based, france).
gold_fact(127, nils, reaches, portugal).
gold_fact(128, marta, reaches, switzerland).
gold_fact(129, jorge, reaches, ecuador).
gold_fact(130, rosa, visits, bern).
gold_fact(131, rosa, visits, bern).
gold_fact(132, rosa, visits, bern).
gold_fact(133, rosa, visits, atenea).
gold_fact(134, rosa, visits, atenea).
gold_fact(135, rosa, visits, atenea).
gold_fact(136, rosa, visits, atenea).
gold_fact(137, rosa, visits, oslo).
gold_fact(138, rosa, visits, oslo).
gold_fact(139, rosa, visits, oslo).
gold_fact(140, rosa, owns, kettle).
gold_fact(141, rosa, owns, kettle).
gold_fact(142, kettle, belongs_to, rosa).
gold_fact(143, rosa, owns, tablet).
gold_fact(144, rosa, owns, tablet).
gold_fact(145, tablet, belongs_to, rosa).
gold_fact(146, rosa, works_at, electra).
gold_fact(147, rosa, works_at, electra).
gold_fact(148, alba, reaches, italy).
gold_fact(149, elena, reaches, grecia).
gold_fact(150, rosa, based, italy).
gold_none(151).
gold_fact(152, sven, reaches, spain).
gold_fact(153, sven, based, ireland).
gold_none(154).
gold_none(155).
gold_fact(156, vera, reaches, italy).
gold_fact(157, madrid, in, spain).
gold_fact(158, madrid, in, spain).
gold_fact(159, oslo, in, norway).
gold_fact(160, oslo, in, norway).
gold_fact(161, paris, in, france).
gold_fact(162, paris, in, france).
gold_fact(163, roma, in, italy).
gold_fact(164, roma, in, italy).
gold_fact(165, quito, in, ecuador).
gold_fact(166, quito, in, ecuador).
gold_fact(167, lima, in, peru).
gold_fact(168, lima, in, peru).
gold_fact(169, dublin, in, ireland).
gold_fact(170, dublin, in, ireland).
gold_fact(171, bern, in, switzerland).
gold_fact(172, bern, in, switzerland).
gold_fact(173, lisboa, in, portugal).
gold_fact(174, lisboa, in, portugal).
gold_fact(175, atenea, in, grecia).
gold_fact(176, atenea, in, grecia).
gold_fact(177, bruno, based, ecuador).
gold_fact(178, elena, visits, lima).
gold_fact(179, elena, visits, lima).
gold_fact(180, elena, visits, lima).
gold_fact(181, elena, visits, bern).
gold_fact(182, elena, visits, bern).
gold_fact(183, elena, visits, bern).
gold_fact(184, elena, visits, atenea).
gold_fact(185, elena, visits, atenea).
gold_fact(186, elena, visits, atenea).
gold_fact(187, elena, owns, compass).
gold_fact(188, elena, owns, compass).
gold_fact(189, compass, belongs_to, elena).
gold_fact(190, elena, owns, mirror).
gold_fact(191, elena, owns, mirror).
gold_fact(192, elena, owns, mirror).
gold_fact(193, mirror, belongs_to, elena).
gold_fact(194, elena, works_at, electra).
gold_fact(195, elena, works_at, electra).
gold_none(196).
gold_none(197).
gold_fact(198, olga, reaches, switzerland).
gold_none(199).
gold_fact(200, ugo, visits, madrid).
gold_fact(201, ugo, visits, madrid).
gold_fact(202, ugo, visits, madrid).
gold_fact(203, ugo, visits, paris).
gold_fact(204, ugo, visits, paris).
gold_fact(205, ugo, visits, paris).
gold_fact(206, ugo, visits, quito).
gold_fact(207, ugo, visits, quito).
gold_fact(208, ugo, visits, quito).
gold_fact(209, ugo, owns, book).
gold_fact(210, ugo, owns, book).
gold_fact(211, book, belongs_to, ugo).
gold_fact(212, ugo, owns, compass).
gold_fact(213, ugo, owns, compass).
gold_fact(214, ugo, owns, compass).
gold_fact(215, compass, belongs_to, ugo).
gold_fact(216, ugo, works_at, helvetia).
gold_fact(217, ugo, works_at, helvetia).
gold_fact(218, carla, reaches, peru).
gold_fact(219, hugo, reaches, france).
gold_fact(220, sven, visits, lisboa).
gold_fact(221, sven, visits, lisboa).
gold_fact(222, sven, visits, lisboa).
gold_fact(223, sven, visits, madrid).
gold_fact(224, sven, visits, madrid).
gold_fact(225, sven, visits, madrid).
gold_fact(226, sven, visits, madrid).
gold_fact(227, sven, visits, paris).
gold_fact(228, sven, visits, paris).
gold_fact(229, sven, visits, paris).
gold_fact(230, sven, owns, mirror).
gold_fact(231, sven, owns, mirror).
gold_fact(232, mirror, belongs_to, sven).
gold_fact(233, sven, owns, violin).
gold_fact(234, sven, owns, violin).
gold_fact(235, violin, belongs_to, sven).
gold_fact(236, sven, works_at, futura).
gold_fact(237, sven, works_at, futura).
gold_fact(238, pablo, reaches, spain).
gold_fact(239, bruno, reaches, ireland).
gold_fact(240, irene, based, norway).
gold_fact(241, marta, reaches, italy).
gold_none(242).
gold_fact(243, marta, reaches, peru).
gold_fact(244, hugo, visits, lisboa).
gold_fact(245, hugo, visits, lisboa).
gold_fact(246, hugo, visits, lisboa).
gold_fact(247, hugo, visits, madrid).
gold_fact(248, hugo, visits, madrid).
gold_fact(249, hugo, visits, madrid).
gold_fact(250, hugo, visits, madrid).
gold_fact(251, hugo, visits, paris).
gold_fact(252, hugo, visits, paris).
gold_fact(253, hugo, visits, paris).
gold_fact(254, hugo, owns, kettle).
gold_fact(255, hugo, owns, kettle).
gold_fact(256, kettle, belongs_to, hugo).
gold_fact(257, hugo, owns, tablet).
gold_fact(258, hugo, owns, tablet).
gold_fact(259, tablet, belongs_to, hugo).
gold_fact(260, hugo, works_at, helvetia).
gold_fact(261, hugo, works_at, helvetia).
gold_fact(262, leo, based, spain).
gold_fact(263, rosa, reaches, grecia).
gold_fact(264, tara, reaches, grecia).
gold_fact(265, quinn, based, spain).
gold_fact(266, kira, visits, oslo).
gold_fact(267, kira, visits, oslo).
gold_fact(268, kira, visits, oslo).
gold_fact(269, kira, visits, roma).
gold_fact(270, kira, visits, roma).
gold_fact(271, kira, visits, roma).
gold_fact(272, kira, visits, roma).
gold_fact(273, kira, visits, lima).
gold_fact(274, kira, visits, lima).
gold_fact(275, kira, visits, lima).
gold_fact(276, kira, owns, book).
gold_fact(277, kira, owns, book).
gold_fact(278, book, belongs_to, kira).
gold_fact(279, kira, owns, compass).
gold_fact(280, kira, owns, compass).
gold_fact(281, compass, belongs_to, kira).
gold_fact(282, kira, works_at, civica).
gold_fact(283, kira, works_at, civica).
gold_fact(284, fabio, reaches, ireland).
gold_fact(285, jorge, reaches, france).
gold_none(286).
gold_fact(287, olga, reaches, grecia).
gold_fact(288, nils, visits, quito).
gold_fact(289, nils, visits, quito).
gold_fact(290, nils, visits, quito).
gold_fact(291, nils, visits, dublin).
gold_fact(292, nils, visits, dublin).
gold_fact(293, nils, visits, dublin).
gold_fact(294, nils, visits, dublin).
gold_fact(295, nils, visits, lisboa).
gold_fact(296, nils, visits, lisboa).
gold_fact(297, nils, visits, lisboa).
gold_fact(298, nils, owns, camera).
gold_fact(299, nils, owns, camera).
gold_fact(300, camera, belongs_to, nils).
gold_fact(301, nils, owns, kettle).
gold_fact(302, nils, owns, kettle).
gold_fact(303, kettle, belongs_to, nils).
gold_fact(304, nils, works_at, futura).
gold_fact(305, nils, works_at, futura).
gold_fact(306, jorge, based, ecuador).
gold_fact(307, pablo, reaches, ireland).
gold_none(308).
gold_none(309).
gold_fact(310, alba, based, norway).
gold_fact(311, greta, reaches, grecia).
gold_fact(312, greta, reaches, norway).
gold_none(313).
gold_fact(314, elena, reaches, peru).
gold_fact(315, kira, reaches, norway).
gold_fact(316, irene, reaches, norway).
gold_none(317).
gold_fact(318, ugo, reaches, ecuador).
gold_fact(319, leo, reaches, france).
gold_fact(320, greta, visits, bern).
gold_fact(321, greta, visits, bern).
gold_fact(322, greta, visits, bern).
gold_fact(323, greta, visits, atenea).
gold_fact(324, greta, visits, atenea).
gold_fact(325, greta, visits, atenea).
gold_fact(326, greta, visits, oslo).
gold_fact(327, greta, visits, oslo).
gold_fact(328, greta, visits, oslo).
gold_fact(329, greta, owns, globe).
gold_fact(330, greta, owns, globe).
gold_fact(331, globe, belongs_to, greta).
gold_fact(332, greta, owns, book).
gold_fact(333, greta, owns, book).
gold_fact(334, greta, owns, book).
gold_fact(335, book, belongs_to, greta).
gold_fact(336, greta, works_at, granito).
gold_fact(337, greta, works_at, granito).
gold_fact(338, kira, reaches, peru).
gold_fact(339, irene, visits, atenea).
gold_fact(340, irene, visits, atenea).
gold_fact(341, irene, visits, atenea).
gold_fact(342, irene, visits, oslo).
gold_fact(343, irene, visits, oslo).
gold_fact(344, irene, visits, oslo).
gold_fact(345, irene, visits, roma).
gold_fact(346, irene, visits, roma).
gold_fact(347, irene, visits, roma).
gold_fact(348, irene, owns, mirror).
gold_fact(349, irene, owns, mirror).
gold_fact(350, mirror, belongs_to, irene).
gold_fact(351, irene, owns, violin).
gold_fact(352, irene, owns, violin).
gold_fact(353, irene, owns, violin).
gold_fact(354, violin, belongs_to, irene).
gold_fact(355, irene, works_at, acme).
gold_fact(356, irene, works_at, acme).
gold_fact(357, bruno, reaches, france).
gold_none(358).
gold_fact(359, nils, reaches, ireland).
gold_fact(360, quinn, reaches, portugal).
gold_fact(361, ugo, reaches, spain).
gold_fact(362, alba, visits, oslo).
gold_fact(363, alba, visits, oslo).
gold_fact(364, alba, visits, oslo).
gold_fact(365, alba, visits, roma).
gold_fact(366, alba, visits, roma).
gold_fact(367, alba, visits, roma).
gold_fact(368, alba, visits, roma).
gold_fact(369, alba, visits, lima).
gold_fact(370, alba, visits, lima).
gold_fact(371, alba, visits, lima).
gold_fact(372, alba, owns, book).
gold_fact(373, alba, owns, book).
gold_fact(374, book, belongs_to, alba).
gold_fact(375, alba, owns, compass).
gold_fact(376, alba, owns, compass).
gold_fact(377, compass, belongs_to, alba).
gold_fact(378, alba, works_at, acme).
gold_fact(379, alba, works_at, acme).
gold_fact(380, acme, located, oslo).
gold_fact(381, acme, located, oslo).
gold_fact(382, borealis, located, quito).
gold_fact(383, borealis, located, quito).
gold_fact(384, civica, located, bern).
gold_fact(385, civica, located, bern).
gold_fact(386, danubio, located, madrid).
gold_fact(387, danubio, located, madrid).
gold_fact(388, electra, located, roma).
gold_fact(389, electra, located, roma).
gold_fact(390, futura, located, dublin).
gold_fact(391, futura, located, dublin).
gold_fact(392, granito, located, atenea).
gold_fact(393, granito, located, atenea).
gold_fact(394, helvetia, located, paris).
gold_fact(395, helvetia, located, paris).
gold_fact(396, olga, based, grecia).
gold_fact(397, sven, reaches, france).
gold_none(398).
gold_fact(399, ugo, reaches, france).
gold_fact(400, leo, visits, paris).
gold_fact(401, leo, visits, paris).
gold_fact(402, leo, visits, paris).
gold_fact(403, leo, visits, quito).
gold_fact(404, leo, visits, quito).
gold_fact(405, leo, visits, quito).
gold_fact(406, leo, visits, dublin).
gold_fact(407, leo, visits, dublin).
gold_fact(408, leo, visits, dublin).
gold_fact(409, leo, owns, tablet).
gold_fact(410, leo, owns, tablet).
gold_fact(411, tablet, belongs_to, leo).
gold_fact(412, leo, owns, lantern).
gold_fact(413, leo, owns, lantern).
gold_fact(414, leo, owns, lantern).
gold_fact(415, lantern, belongs_to, leo).
gold_fact(416, leo, works_at, danubio).
gold_fact(417, leo, works_at, danubio).
gold_fact(418, kira, reaches, italy).
gold_fact(419, bruno, visits, paris).
gold_fact(420, bruno, visits, paris).
gold_fact(421, bruno, visits, paris).
gold_fact(422, bruno, visits, quito).
gold_fact(423, bruno, visits, quito).
gold_fact(424, bruno, visits, quito).
gold_fact(425, bruno, visits, dublin).
gold_fact(426, bruno, visits, dublin).
gold_fact(427, bruno, visits, dublin).
gold_fact(428, bruno, owns, tablet).
gold_fact(429, bruno, owns, tablet).
gold_fact(430, tablet, belongs_to, bruno).
gold_fact(431, bruno, owns, lantern).
gold_fact(432, bruno, owns, lantern).
gold_fact(433, bruno, owns, lantern).
gold_fact(434, lantern, belongs_to, bruno).
gold_fact(435, bruno, works_at, borealis).
gold_fact(436, bruno, works_at, borealis).
gold_fact(437, diego, reaches, portugal).
gold_none(438).
gold_fact(439, carla, visits, roma).
gold_fact(440, carla, visits, roma).
gold_fact(441, carla, visits, roma).
gold_fact(442, carla, visits, lima).
gold_fact(443, carla, visits, lima).
gold_fact(444, carla, visits, lima).
gold_fact(445, carla, visits, bern).
gold_fact(446, carla, visits, bern).
gold_fact(447, carla, visits, bern).
gold_fact(448, carla, owns, violin).
gold_fact(449, carla, owns, violin).
gold_fact(450, violin, belongs_to, carla).
gold_fact(451, carla, owns, globe).
gold_fact(452, carla, owns, globe).
gold_fact(453, carla, owns, globe).
gold_fact(454, globe, belongs_to, carla).
gold_fact(455, carla, works_at, civica).
gold_fact(456, carla, works_at, civica).
gold_fact(457, kira, based, switzerland).
gold_fact(458, olga, visits, lima).
gold_fact(459, olga, visits, lima).
gold_fact(460, olga, visits, lima).
gold_fact(461, olga, visits, bern).
gold_fact(462, olga, visits, bern).
gold_fact(463, olga, visits, bern).
gold_fact(464, olga, visits, bern).
gold_fact(465, olga, visits, atenea).
gold_fact(466, olga, visits, atenea).
gold_fact(467, olga, visits, atenea).
gold_fact(468, olga, owns, compass).
gold_fact(469, olga, owns, compass).
gold_fact(470, compass, belongs_to, olga).
gold_fact(471, olga, owns, mirror).
gold_fact(472, olga, owns, mirror).
gold_fact(473, mirror, belongs_to, olga).
gold_fact(474, olga, works_at, granito).
gold_fact(475, olga, works_at, granito).
gold_fact(476, vera, based, norway).
gold_fact(477, vera, visits, oslo).
gold_fact(478, vera, visits, oslo).
gold_fact(479, vera, visits, oslo).
gold_fact(480, vera, visits, roma).
gold_fact(481, vera, visits, roma).
gold_fact(482, vera, visits, roma).
gold_fact(483, vera, visits, roma).
gold_fact(484, vera, visits, lima).
gold_fact(485, vera, visits, lima).
gold_fact(486, vera, visits, lima).
gold_fact(487, vera, owns, tablet).
gold_fact(488, vera, owns, tablet).
gold_fact(489, tablet, belongs_to, vera).
gold_fact(490, vera, owns, lantern).
gold_fact(491, vera, owns, lantern).
gold_fact(492, lantern, belongs_to, vera).
gold_fact(493, vera, works_at, acme).
gold_fact(494, vera, works_at, acme).
gold_fact(495, carla, reaches, italy).
gold_fact(496, vera, reaches, norway).
gold_fact(497, leo, reaches, ecuador).
gold_fact(498, tara, visits, atenea).
gold_fact(499, tara, visits, atenea).
gold_fact(500, tara, visits, atenea).
gold_fact(501, tara, visits, oslo).
gold_fact(502, tara, visits, oslo).
gold_fact(503, tara, visits, oslo).
gold_fact(504, tara, visits, oslo).
gold_fact(505, tara, visits, roma).
gold_fact(506, tara, visits, roma).
gold_fact(507, tara, visits, roma).
gold_fact(508, tara, owns, paddle).
gold_fact(509, tara, owns, paddle).
gold_fact(510, paddle, belongs_to, tara).
gold_fact(511, tara, owns, camera).
gold_fact(512, tara, owns, camera).
gold_fact(513, camera, belongs_to, tara).
gold_fact(514, tara, works_at, granito).
gold_fact(515, tara, works_at, granito).
gold_fact(516, leo, reaches, ireland).
gold_fact(517, vera, reaches, peru).
gold_fact(518, nils, reaches, ecuador).
gold_none(519).
