heldout(alba, norway, reaches).
heldout(bruno, ecuador, reaches).
heldout(carla, switzerland, reaches).
heldout(diego, ecuador, reaches).
heldout(elena, switzerland, reaches).
heldout(fabio, spain, reaches).
heldout(greta, switzerland, reaches).
heldout(hugo, spain, reaches).
heldout(irene, italy, reaches).
heldout(jorge, spain, reaches).
heldout(quinn, ireland, reaches).
heldout(rosa, switzerland, reaches).
heldout(sven, portugal, reaches).
heldout(carla, switzerland, based).
heldout(diego, spain, based).
heldout(elena, italy, based).
heldout(fabio, ireland, based).
heldout(greta, grecia, based).
heldout(hugo, france, based).
heldout(tara, grecia, based).
heldout(ugo, france, based).
