cmake_minimum_required(VERSION 3.16)
project(dynamic C)
enable_testing()
add_library(lib STATIC src/lib.c)
add_executable(t_lib tests/t_lib.c)
target_link_libraries(t_lib lib)
target_include_directories(t_lib PRIVATE src)
add_executable(t_inc tests/t_inc.c)
add_test(NAME lib_ok COMMAND t_lib)
add_test(NAME inc_ok COMMAND t_inc)
