memfact(alice,followed,white_rabbit,1.0,1).
memfact(alice,drink,bottle,1.0,1).
memfact(alice,eat,cake,1.0,1).
memfact(alice,peeped,book,1.0,1).
memfact(alice,has,sister,1.0,1).
memfact(alice,waved,fan,1.0,1).
memfact(alice,found,key,1.0,1).
memfact(alice,entered,garden,1.0,1).
memfact(alice,defied,court,1.0,1).
memfact(alice,played,croquet,1.0,1).
memfact(alice,held,flamingo,1.0,1).
memfact(alice,recited,poem,1.0,1).
memfact(alice,swam,pool,1.0,1).
memfact(alice,meet,caterpillar,1.0,1).
memfact(alice,meet,hatter,1.0,1).
memfact(alice,meet,queen,1.0,1).
memfact(alice,meet,cheshire_cat,1.0,1).
memfact(alice,meet,mock_turtle,1.0,1).
memfact(alice,meet,duchess,1.0,1).
memfact(white_rabbit,carries,watch,1.0,1).
memfact(white_rabbit,wears,waistcoat,1.0,1).
memfact(white_rabbit,dropped,fan,1.0,1).
memfact(white_rabbit,read,accusation,1.0,1).
memfact(caterpillar,smokes,hookah,1.0,1).
memfact(caterpillar,asked,alice,1.0,1).
memfact(caterpillar,advised,alice,1.0,1).
memfact(cheshire_cat,has,grin,1.0,1).
memfact(cheshire_cat,left,grin,1.0,1).
memfact(hatter,hosts,tea_party,1.0,1).
memfact(hatter,asked,riddle,1.0,1).
memfact(dormouse,attends,tea_party,1.0,1).
memfact(dormouse,told,story,1.0,1).
memfact(march_hare,offered,wine,1.0,1).
memfact(duchess,nurses,baby,1.0,1).
memfact(baby,turned,pig,1.0,1).
memfact(queen,plays,croquet,1.0,1).
memfact(queen,threatened,alice,1.0,1).
memfact(king,judges,knave,1.0,1).
memfact(gardeners,painted,roses,1.0,1).
memfact(mock_turtle,sing,quadrille,1.0,1).
memfact(gryphon,led,alice,1.0,1).
memfact(hatter,attended,trial,1.0,1).
memfact(sister,woke,alice,1.0,1).
memfact(sister,read,book,1.0,1).
memfact(footman,carries,letter,1.0,1).
memfact(alice_in_wonderland,is,book,1.0,1).
memfact(alice_in_wonderland,author,carroll,1.0,1).
memfact(alice,appears_in,alice_in_wonderland,1.0,1).
memfact(white_rabbit,appears_in,alice_in_wonderland,1.0,1).
memfact(hatter,appears_in,alice_in_wonderland,1.0,1).
memfact(queen,appears_in,alice_in_wonderland,1.0,1).
memfact(cheshire_cat,appears_in,alice_in_wonderland,1.0,1).
memfact(caterpillar,appears_in,alice_in_wonderland,1.0,1).
provfact(alice,followed,white_rabbit,curated_alice_1,none,active).
provfact(alice,drink,bottle,curated_alice_2,none,active).
provfact(alice,eat,cake,curated_alice_3,none,active).
provfact(alice,peeped,book,curated_alice_4,none,active).
provfact(alice,has,sister,curated_alice_5,none,active).
provfact(alice,waved,fan,curated_alice_6,none,active).
provfact(alice,found,key,curated_alice_7,none,active).
provfact(alice,entered,garden,curated_alice_8,none,active).
provfact(alice,defied,court,curated_alice_9,none,active).
provfact(alice,played,croquet,curated_alice_10,none,active).
provfact(alice,held,flamingo,curated_alice_11,none,active).
provfact(alice,recited,poem,curated_alice_12,none,active).
provfact(alice,swam,pool,curated_alice_13,none,active).
provfact(alice,meet,caterpillar,curated_alice_14,none,active).
provfact(alice,meet,hatter,curated_alice_15,none,active).
provfact(alice,meet,queen,curated_alice_16,none,active).
provfact(alice,meet,cheshire_cat,curated_alice_17,none,active).
provfact(alice,meet,mock_turtle,curated_alice_18,none,active).
provfact(alice,meet,duchess,curated_alice_19,none,active).
provfact(white_rabbit,carries,watch,curated_alice_20,none,active).
provfact(white_rabbit,wears,waistcoat,curated_alice_21,none,active).
provfact(white_rabbit,dropped,fan,curated_alice_22,none,active).
provfact(white_rabbit,read,accusation,curated_alice_23,none,active).
provfact(caterpillar,smokes,hookah,curated_alice_24,none,active).
provfact(caterpillar,asked,alice,curated_alice_25,none,active).
provfact(caterpillar,advised,alice,curated_alice_26,none,active).
provfact(cheshire_cat,has,grin,curated_alice_27,none,active).
provfact(cheshire_cat,left,grin,curated_alice_28,none,active).
provfact(hatter,hosts,tea_party,curated_alice_29,none,active).
provfact(hatter,asked,riddle,curated_alice_30,none,active).
provfact(dormouse,attends,tea_party,curated_alice_31,none,active).
provfact(dormouse,told,story,curated_alice_32,none,active).
provfact(march_hare,offered,wine,curated_alice_33,none,active).
provfact(duchess,nurses,baby,curated_alice_34,none,active).
provfact(baby,turned,pig,curated_alice_35,none,active).
provfact(queen,plays,croquet,curated_alice_36,none,active).
provfact(queen,threatened,alice,curated_alice_37,none,active).
provfact(king,judges,knave,curated_alice_38,none,active).
provfact(gardeners,painted,roses,curated_alice_39,none,active).
provfact(mock_turtle,sing,quadrille,curated_alice_40,none,active).
provfact(gryphon,led,alice,curated_alice_41,none,active).
provfact(hatter,attended,trial,curated_alice_42,none,active).
provfact(sister,woke,alice,curated_alice_43,none,active).
provfact(sister,read,book,curated_alice_44,none,active).
provfact(footman,carries,letter,curated_alice_45,none,active).
provfact(alice_in_wonderland,is,book,curated_alice_46,none,active).
provfact(alice_in_wonderland,author,carroll,curated_alice_47,none,active).
provfact(alice,appears_in,alice_in_wonderland,curated_alice_48,none,active).
provfact(white_rabbit,appears_in,alice_in_wonderland,curated_alice_49,none,active).
provfact(hatter,appears_in,alice_in_wonderland,curated_alice_50,none,active).
provfact(queen,appears_in,alice_in_wonderland,curated_alice_51,none,active).
provfact(cheshire_cat,appears_in,alice_in_wonderland,curated_alice_52,none,active).
provfact(caterpillar,appears_in,alice_in_wonderland,curated_alice_53,none,active).
gapseq(0).
