/* ============================================================
   cognitive_learning: Advanced Learning Paradigms on the Peircean Triad.
   Pure C99, zero tensors, zero backprop, fail-closed verification.

   New learning paradigms:
     1. ACTIVE EPISTEMIC INQUIRY: Abduction-driven curiosity that
        diagnoses missing knowledge gaps and formulates targeted questions.
     2. NON-MONOTONIC BELIEF REVISION: Refines rules with exception
        guards (defeasible reasoning) when encountering counterexamples.
     3. SYMBOLIC SELF-SUPERVISED LEARNING: Masked edge reconstruction
        and autonomous confidence calibration without human supervision.
     4. PEIRCEAN INQUIRY CYCLE: Continuous loop uniting induction,
        deduction, and abduction into autonomous scientific discovery.

   Design principles:
     - HARDCODING=0: Lexical and structural parameters are dynamic.
     - Fail-closed: Never asserts unverified edges.
   ============================================================ */

#ifndef COGNITIVE_LEARNING_H
#define COGNITIVE_LEARNING_H

#include <stdint.h>
#include <stddef.h>
#include "graph.h"
#include "graph_reasoning.h"

#define MAX_INQUIRY_QUESTIONS 16
#define MAX_EXCEPTIONS 32

/* Epistemic state of an inquiry */
typedef enum
{
    INQUIRY_UNKNOWN = 0,
    INQUIRY_HYPOTHESIZED,
    INQUIRY_CONFIRMED,
    INQUIRY_REFUTED
} INQUIRY_STATUS;

/* A targeted epistemic inquiry question generated by abduction */
typedef struct
{
    SYMBOL_ID target_subj;
    SYMBOL_ID target_rel;
    SYMBOL_ID target_obj;
    SYMBOL_ID missing_subj;
    SYMBOL_ID missing_rel;
    SYMBOL_ID missing_obj;
    float     priority;          /* Plausibility / confidence of the rule */
    char      question[256];     /* Natural language inquiry */
    char      search_term[128];  /* Keywords for search / scraper */
} EPISTEMIC_INQUIRY;

/* An exception rule for non-monotonic belief revision */
typedef struct
{
    uint32_t  base_rule_idx;
    SYMBOL_ID exception_entity;  /* Entity that overrides the rule */
    char      rationale[128];
} BELIEF_EXCEPTION;

/* Self-supervised benchmark metrics */
typedef struct
{
    uint32_t total_masked;
    uint32_t reconstructed;
    float    reconstruction_rate; /* reconstructed / total_masked */
    uint32_t false_positives;     /* Must stay 0 */
} SELF_SUPERVISED_METRICS;

/* Autonomous cognitive learner state */
typedef struct
{
    GRAPH_RULE_BASE   rule_base;
    BELIEF_EXCEPTION  exceptions[MAX_EXCEPTIONS];
    uint32_t          num_exceptions;
    uint32_t          cycle_count;
} COGNITIVE_LEARNER;

/* ---- Cognitive Learning API ---- */

/* Initialize cognitive learner */
void CognitiveLearnerInit(COGNITIVE_LEARNER *learner, float min_confidence, uint32_t min_support);

/* 1. Active Epistemic Inquiry: Given an unknown goal, abduce hypotheses
   and formulate prioritized targeted inquiry questions to resolve it. */
uint32_t CognitiveFormulateInquiry(const GRAPH *graph,
                                   const COGNITIVE_LEARNER *learner,
                                   SYMBOL_ID subject,
                                   SYMBOL_ID relation,
                                   SYMBOL_ID object,
                                   EPISTEMIC_INQUIRY *inquiries,
                                   uint32_t max_inquiries);

/* Assimilate newly acquired evidence from an inquiry response */
int CognitiveAssimilateEvidence(GRAPH *graph,
                                COGNITIVE_LEARNER *learner,
                                SYMBOL_ID subject,
                                SYMBOL_ID relation,
                                SYMBOL_ID object);

/* 2. Non-Monotonic Belief Revision: Register an exception when a rule
   is contradicted by an empirical override. */
int CognitiveRegisterException(COGNITIVE_LEARNER *learner,
                               uint32_t rule_idx,
                               SYMBOL_ID exception_entity,
                               const char *rationale);

/* Check if a candidate derivation is blocked by an exception */
int CognitiveIsException(const COGNITIVE_LEARNER *learner,
                         uint32_t rule_idx,
                         SYMBOL_ID entity);

/* 3. Symbolic Self-Supervised Learning (Masked Graph Discovery):
   Randomly masks a fraction of edges, attempts to reconstruct them via
   abduction & deduction, and measures autonomous learning fidelity. */
SELF_SUPERVISED_METRICS CognitiveSelfSupervisedTrain(GRAPH *graph,
                                                    COGNITIVE_LEARNER *learner,
                                                    uint32_t mask_count);

/* 4. Complete Peircean Inquiry Cycle:
   Observation -> Rule Induction -> Deductive Closure -> Active Abduction.
   Returns count of newly deduced knowledge units. */
uint32_t CognitiveRunInquiryCycle(GRAPH *graph, COGNITIVE_LEARNER *learner);

#endif /* COGNITIVE_LEARNING_H */
