gold_fact(1, pablo, lives_in, milan).
gold_fact(2, pablo, lives_in, milan).
gold_fact(3, pablo, works_in, bern).
gold_fact(4, pablo, works_in, bern).
gold_fact(5, pablo, visits, quito).
gold_fact(6, pablo, visits, quito).
gold_fact(7, pablo, visits, dublin).
gold_fact(8, pablo, visits, dublin).
gold_fact(9, pablo, visits, madrid).
gold_fact(10, pablo, visits, madrid).
gold_fact(11, pablo, owns, lamp).
gold_fact(12, pablo, owns, lamp).
gold_fact(13, pablo, owns, lamp).
gold_fact(14, lamp, belongs_to, pablo).
gold_fact(15, pablo, owns, book).
gold_fact(16, pablo, owns, book).
gold_fact(17, pablo, owns, book).
gold_fact(18, pablo, owns, book).
gold_fact(19, book, belongs_to, pablo).
gold_fact(20, leo, lives_in, lyon).
gold_fact(21, leo, lives_in, lyon).
gold_fact(22, leo, lives_in, oslo).
gold_fact(23, leo, works_in, lima).
gold_fact(24, leo, works_in, lima).
gold_fact(25, leo, visits, roma).
gold_fact(26, leo, visits, roma).
gold_fact(27, leo, visits, quito).
gold_fact(28, leo, visits, quito).
gold_fact(29, leo, visits, dublin).
gold_fact(30, leo, visits, dublin).
gold_fact(31, leo, owns, watch).
gold_fact(32, leo, owns, watch).
gold_fact(33, leo, owns, watch).
gold_fact(34, watch, belongs_to, leo).
gold_fact(35, leo, owns, globe).
gold_fact(36, leo, owns, globe).
gold_fact(37, leo, owns, globe).
gold_fact(38, leo, owns, globe).
gold_fact(39, globe, belongs_to, leo).
gold_fact(40, alba, reaches, spain).
gold_none(41).
gold_none(42).
gold_fact(43, bruno, reaches, norway).
gold_fact(44, jorge, lives_in, lyon).
gold_fact(45, jorge, lives_in, lyon).
gold_fact(46, jorge, works_in, lima).
gold_fact(47, jorge, works_in, lima).
gold_fact(48, jorge, visits, roma).
gold_fact(49, jorge, visits, roma).
gold_fact(50, jorge, visits, quito).
gold_fact(51, jorge, visits, quito).
gold_fact(52, jorge, visits, dublin).
gold_fact(53, jorge, visits, dublin).
gold_fact(54, jorge, owns, watch).
gold_fact(55, jorge, owns, watch).
gold_fact(56, jorge, owns, watch).
gold_fact(57, watch, belongs_to, jorge).
gold_fact(58, jorge, owns, globe).
gold_fact(59, jorge, owns, globe).
gold_fact(60, jorge, owns, globe).
gold_fact(61, jorge, owns, globe).
gold_fact(62, globe, belongs_to, jorge).
gold_none(63).
gold_fact(64, lucia, lives_in, quito).
gold_fact(65, lucia, lives_in, quito).
gold_fact(66, lucia, works_in, madrid).
gold_fact(67, lucia, works_in, madrid).
gold_fact(68, lucia, visits, lima).
gold_fact(69, lucia, visits, lima).
gold_fact(70, lucia, visits, bern).
gold_fact(71, lucia, visits, bern).
gold_fact(72, lucia, visits, barcelona).
gold_fact(73, lucia, visits, barcelona).
gold_fact(74, lucia, owns, radio).
gold_fact(75, lucia, owns, radio).
gold_fact(76, lucia, owns, radio).
gold_fact(77, radio, belongs_to, lucia).
gold_fact(78, lucia, owns, tablet).
gold_fact(79, lucia, owns, tablet).
gold_fact(80, lucia, owns, tablet).
gold_fact(81, lucia, owns, tablet).
gold_fact(82, tablet, belongs_to, lucia).
gold_fact(83, julia, reaches, norway).
gold_fact(84, vera, reaches, france).
gold_fact(85, nora, reaches, france).
gold_fact(86, hugo, reaches, norway).
gold_none(87).
gold_none(88).
gold_none(89).
gold_fact(90, diego, reaches, spain).
gold_none(91).
gold_fact(92, teo, reaches, ireland).
gold_fact(93, hugo, reaches, france).
gold_fact(94, teo, reaches, ecuador).
gold_fact(95, ana, reaches, norway).
gold_none(96).
gold_fact(97, nora, lives_in, paris).
gold_fact(98, nora, lives_in, paris).
gold_fact(99, nora, lives_in, lyon).
gold_fact(100, nora, works_in, quito).
gold_fact(101, nora, works_in, quito).
gold_fact(102, nora, visits, lyon).
gold_fact(103, nora, visits, lyon).
gold_fact(104, nora, visits, milan).
gold_fact(105, nora, visits, milan).
gold_fact(106, nora, visits, milan).
gold_fact(107, nora, visits, lima).
gold_fact(108, nora, visits, lima).
gold_fact(109, nora, owns, camera).
gold_fact(110, nora, owns, camera).
gold_fact(111, nora, owns, camera).
gold_fact(112, camera, belongs_to, nora).
gold_fact(113, nora, owns, chess).
gold_fact(114, nora, owns, chess).
gold_fact(115, nora, owns, chess).
gold_fact(116, chess, belongs_to, nora).
gold_fact(117, dario, reaches, spain).
gold_fact(118, gaia, reaches, norway).
gold_fact(119, eric, reaches, italy).
gold_fact(120, dario, reaches, france).
gold_fact(121, marcos, reaches, norway).
gold_fact(122, diego, lives_in, bern).
gold_fact(123, diego, lives_in, bern).
gold_fact(124, diego, works_in, bergen).
gold_fact(125, diego, works_in, bergen).
gold_fact(126, diego, visits, madrid).
gold_fact(127, diego, visits, madrid).
gold_fact(128, diego, visits, oslo).
gold_fact(129, diego, visits, oslo).
gold_fact(130, diego, visits, paris).
gold_fact(131, diego, visits, paris).
gold_fact(132, diego, owns, drum).
gold_fact(133, diego, owns, drum).
gold_fact(134, diego, owns, drum).
gold_fact(135, drum, belongs_to, diego).
gold_fact(136, diego, owns, camera).
gold_fact(137, diego, owns, camera).
gold_fact(138, diego, owns, camera).
gold_fact(139, diego, owns, camera).
gold_fact(140, camera, belongs_to, diego).
gold_fact(141, yago, reaches, ireland).
gold_fact(142, pedro, reaches, italy).
gold_fact(143, bruno, reaches, spain).
gold_none(144).
gold_fact(145, ana, reaches, france).
gold_fact(146, ivan, reaches, france).
gold_fact(147, leo, reaches, italy).
gold_fact(148, hugo, reaches, italy).
gold_fact(149, hugo, lives_in, barcelona).
gold_fact(150, hugo, lives_in, barcelona).
gold_fact(151, hugo, works_in, lyon).
gold_fact(152, hugo, works_in, lyon).
gold_fact(153, hugo, visits, oslo).
gold_fact(154, hugo, visits, oslo).
gold_fact(155, hugo, visits, paris).
gold_fact(156, hugo, visits, paris).
gold_fact(157, hugo, visits, paris).
gold_fact(158, hugo, visits, roma).
gold_fact(159, hugo, visits, roma).
gold_fact(160, hugo, owns, tablet).
gold_fact(161, hugo, owns, tablet).
gold_fact(162, hugo, owns, tablet).
gold_fact(163, tablet, belongs_to, hugo).
gold_fact(164, hugo, owns, bicycle).
gold_fact(165, hugo, owns, bicycle).
gold_fact(166, hugo, owns, bicycle).
gold_fact(167, bicycle, belongs_to, hugo).
gold_fact(168, elena, reaches, peru).
gold_fact(169, diego, reaches, norway).
gold_fact(170, maria, reaches, france).
gold_fact(171, jorge, reaches, italy).
gold_none(172).
gold_fact(173, luis, reaches, italy).
gold_none(174).
gold_fact(175, pablo, reaches, spain).
gold_none(176).
gold_fact(177, yago, reaches, spain).
gold_fact(178, eric, lives_in, barcelona).
gold_fact(179, eric, lives_in, barcelona).
gold_fact(180, eric, works_in, lyon).
gold_fact(181, eric, works_in, lyon).
gold_fact(182, eric, visits, oslo).
gold_fact(183, eric, visits, oslo).
gold_fact(184, eric, visits, paris).
gold_fact(185, eric, visits, paris).
gold_fact(186, eric, visits, paris).
gold_fact(187, eric, visits, roma).
gold_fact(188, eric, visits, roma).
gold_fact(189, eric, owns, pen).
gold_fact(190, eric, owns, pen).
gold_fact(191, eric, owns, pen).
gold_fact(192, pen, belongs_to, eric).
gold_fact(193, eric, owns, lamp).
gold_fact(194, eric, owns, lamp).
gold_fact(195, eric, owns, lamp).
gold_fact(196, lamp, belongs_to, eric).
gold_fact(197, ana, lives_in, oslo).
gold_fact(198, ana, lives_in, oslo).
gold_fact(199, ana, works_in, roma).
gold_fact(200, ana, works_in, roma).
gold_fact(201, ana, visits, bergen).
gold_fact(202, ana, visits, bergen).
gold_fact(203, ana, visits, lyon).
gold_fact(204, ana, visits, lyon).
gold_fact(205, ana, visits, milan).
gold_fact(206, ana, visits, milan).
gold_fact(207, ana, owns, pen).
gold_fact(208, ana, owns, pen).
gold_fact(209, ana, owns, pen).
gold_fact(210, pen, belongs_to, ana).
gold_fact(211, ana, owns, lamp).
gold_fact(212, ana, owns, lamp).
gold_fact(213, ana, owns, lamp).
gold_fact(214, ana, owns, lamp).
gold_fact(215, lamp, belongs_to, ana).
gold_fact(216, maria, lives_in, madrid).
gold_fact(217, maria, lives_in, madrid).
gold_fact(218, maria, works_in, paris).
gold_fact(219, maria, works_in, paris).
gold_fact(220, maria, visits, barcelona).
gold_fact(221, maria, visits, barcelona).
gold_fact(222, maria, visits, bergen).
gold_fact(223, maria, visits, bergen).
gold_fact(224, maria, visits, lyon).
gold_fact(225, maria, visits, lyon).
gold_fact(226, maria, owns, book).
gold_fact(227, maria, owns, book).
gold_fact(228, maria, owns, book).
gold_fact(229, book, belongs_to, maria).
gold_fact(230, maria, owns, watch).
gold_fact(231, maria, owns, watch).
gold_fact(232, maria, owns, watch).
gold_fact(233, maria, owns, watch).
gold_fact(234, watch, belongs_to, maria).
gold_fact(235, pedro, reaches, norway).
gold_none(236).
gold_fact(237, sara, lives_in, dublin).
gold_fact(238, sara, lives_in, dublin).
gold_fact(239, sara, works_in, oslo).
gold_fact(240, sara, works_in, oslo).
gold_fact(241, sara, visits, bern).
gold_fact(242, sara, visits, bern).
gold_fact(243, sara, visits, barcelona).
gold_fact(244, sara, visits, barcelona).
gold_fact(245, sara, visits, barcelona).
gold_fact(246, sara, visits, bergen).
gold_fact(247, sara, visits, bergen).
gold_fact(248, sara, owns, globe).
gold_fact(249, sara, owns, globe).
gold_fact(250, sara, owns, globe).
gold_fact(251, globe, belongs_to, sara).
gold_fact(252, sara, owns, guitar).
gold_fact(253, sara, owns, guitar).
gold_fact(254, sara, owns, guitar).
gold_fact(255, guitar, belongs_to, sara).
gold_none(256).
gold_fact(257, dario, lives_in, bern).
gold_fact(258, dario, lives_in, bern).
gold_fact(259, dario, works_in, bergen).
gold_fact(260, dario, works_in, bergen).
gold_fact(261, dario, visits, madrid).
gold_fact(262, dario, visits, madrid).
gold_fact(263, dario, visits, oslo).
gold_fact(264, dario, visits, oslo).
gold_fact(265, dario, visits, paris).
gold_fact(266, dario, visits, paris).
gold_fact(267, dario, owns, book).
gold_fact(268, dario, owns, book).
gold_fact(269, dario, owns, book).
gold_fact(270, book, belongs_to, dario).
gold_fact(271, dario, owns, watch).
gold_fact(272, dario, owns, watch).
gold_fact(273, dario, owns, watch).
gold_fact(274, dario, owns, watch).
gold_fact(275, watch, belongs_to, dario).
gold_fact(276, yago, lives_in, milan).
gold_fact(277, yago, lives_in, milan).
gold_fact(278, yago, works_in, bern).
gold_fact(279, yago, works_in, bern).
gold_fact(280, yago, visits, quito).
gold_fact(281, yago, visits, quito).
gold_fact(282, yago, visits, dublin).
gold_fact(283, yago, visits, dublin).
gold_fact(284, yago, visits, dublin).
gold_fact(285, yago, visits, madrid).
gold_fact(286, yago, visits, madrid).
gold_fact(287, yago, owns, radio).
gold_fact(288, yago, owns, radio).
gold_fact(289, yago, owns, radio).
gold_fact(290, radio, belongs_to, yago).
gold_fact(291, yago, owns, tablet).
gold_fact(292, yago, owns, tablet).
gold_fact(293, yago, owns, tablet).
gold_fact(294, tablet, belongs_to, yago).
gold_fact(295, luis, reaches, ecuador).
gold_none(296).
gold_none(297).
gold_fact(298, carmen, reaches, france).
gold_fact(299, julia, reaches, france).
gold_fact(300, madrid, in, spain).
gold_fact(301, madrid, in, spain).
gold_fact(302, barcelona, in, spain).
gold_fact(303, barcelona, in, spain).
gold_fact(304, oslo, in, norway).
gold_fact(305, oslo, in, norway).
gold_fact(306, bergen, in, norway).
gold_fact(307, bergen, in, norway).
gold_fact(308, paris, in, france).
gold_fact(309, paris, in, france).
gold_fact(310, lyon, in, france).
gold_fact(311, lyon, in, france).
gold_fact(312, roma, in, italy).
gold_fact(313, roma, in, italy).
gold_fact(314, milan, in, italy).
gold_fact(315, milan, in, italy).
gold_fact(316, quito, in, ecuador).
gold_fact(317, quito, in, ecuador).
gold_fact(318, lima, in, peru).
gold_fact(319, lima, in, peru).
gold_fact(320, dublin, in, ireland).
gold_fact(321, dublin, in, ireland).
gold_fact(322, bern, in, switzerland).
gold_fact(323, bern, in, switzerland).
gold_fact(324, elena, reaches, switzerland).
gold_fact(325, mia, reaches, italy).
gold_fact(326, maria, reaches, norway).
gold_fact(327, lucia, reaches, switzerland).
gold_none(328).
gold_fact(329, leo, reaches, ecuador).
gold_fact(330, ines, lives_in, quito).
gold_fact(331, ines, lives_in, quito).
gold_fact(332, ines, works_in, madrid).
gold_fact(333, ines, works_in, madrid).
gold_fact(334, ines, visits, lima).
gold_fact(335, ines, visits, lima).
gold_fact(336, ines, visits, bern).
gold_fact(337, ines, visits, bern).
gold_fact(338, ines, visits, bern).
gold_fact(339, ines, visits, barcelona).
gold_fact(340, ines, visits, barcelona).
gold_fact(341, ines, owns, chess).
gold_fact(342, ines, owns, chess).
gold_fact(343, ines, owns, chess).
gold_fact(344, chess, belongs_to, ines).
gold_fact(345, ines, owns, pen).
gold_fact(346, ines, owns, pen).
gold_fact(347, ines, owns, pen).
gold_fact(348, pen, belongs_to, ines).
gold_fact(349, marcos, lives_in, lima).
gold_fact(350, marcos, lives_in, lima).
gold_fact(351, marcos, works_in, barcelona).
gold_fact(352, marcos, works_in, barcelona).
gold_fact(353, marcos, visits, dublin).
gold_fact(354, marcos, visits, dublin).
gold_fact(355, marcos, visits, madrid).
gold_fact(356, marcos, visits, madrid).
gold_fact(357, marcos, visits, madrid).
gold_fact(358, marcos, visits, oslo).
gold_fact(359, marcos, visits, oslo).
gold_fact(360, marcos, owns, chess).
gold_fact(361, marcos, owns, chess).
gold_fact(362, marcos, owns, chess).
gold_fact(363, chess, belongs_to, marcos).
gold_fact(364, marcos, owns, pen).
gold_fact(365, marcos, owns, pen).
gold_fact(366, marcos, owns, pen).
gold_fact(367, pen, belongs_to, marcos).
gold_none(368).
gold_fact(369, luis, lives_in, bergen).
gold_fact(370, luis, lives_in, bergen).
gold_fact(371, luis, works_in, milan).
gold_fact(372, luis, works_in, milan).
gold_fact(373, luis, visits, paris).
gold_fact(374, luis, visits, paris).
gold_fact(375, luis, visits, roma).
gold_fact(376, luis, visits, roma).
gold_fact(377, luis, visits, roma).
gold_fact(378, luis, visits, quito).
gold_fact(379, luis, visits, quito).
gold_fact(380, luis, owns, guitar).
gold_fact(381, luis, owns, guitar).
gold_fact(382, luis, owns, guitar).
gold_fact(383, guitar, belongs_to, luis).
gold_fact(384, luis, owns, radio).
gold_fact(385, luis, owns, radio).
gold_fact(386, luis, owns, radio).
gold_fact(387, radio, belongs_to, luis).
gold_fact(388, teo, reaches, spain).
gold_none(389).
gold_fact(390, dario, reaches, norway).
gold_fact(391, vera, reaches, italy).
gold_fact(392, leo, reaches, ireland).
gold_fact(393, gaia, reaches, switzerland).
gold_fact(394, ines, reaches, spain).
gold_fact(395, sofia, reaches, peru).
gold_fact(396, alba, reaches, france).
gold_fact(397, nora, reaches, italy).
gold_fact(398, ivan, reaches, ecuador).
gold_none(399).
gold_fact(400, alba, reaches, norway).
gold_fact(401, mia, reaches, peru).
gold_fact(402, vera, lives_in, oslo).
gold_fact(403, vera, lives_in, oslo).
gold_fact(404, vera, works_in, roma).
gold_fact(405, vera, works_in, roma).
gold_fact(406, vera, visits, bergen).
gold_fact(407, vera, visits, bergen).
gold_fact(408, vera, visits, lyon).
gold_fact(409, vera, visits, lyon).
gold_fact(410, vera, visits, lyon).
gold_fact(411, vera, visits, milan).
gold_fact(412, vera, visits, milan).
gold_fact(413, vera, owns, pen).
gold_fact(414, vera, owns, pen).
gold_fact(415, vera, owns, pen).
gold_fact(416, pen, belongs_to, vera).
gold_fact(417, vera, owns, lamp).
gold_fact(418, vera, owns, lamp).
gold_fact(419, vera, owns, lamp).
gold_fact(420, lamp, belongs_to, vera).
gold_fact(421, bruno, lives_in, lima).
gold_fact(422, bruno, lives_in, lima).
gold_fact(423, bruno, works_in, barcelona).
gold_fact(424, bruno, works_in, barcelona).
gold_fact(425, bruno, visits, dublin).
gold_fact(426, bruno, visits, dublin).
gold_fact(427, bruno, visits, madrid).
gold_fact(428, bruno, visits, madrid).
gold_fact(429, bruno, visits, oslo).
gold_fact(430, bruno, visits, oslo).
gold_fact(431, bruno, owns, globe).
gold_fact(432, bruno, owns, globe).
gold_fact(433, bruno, owns, globe).
gold_fact(434, globe, belongs_to, bruno).
gold_fact(435, bruno, owns, guitar).
gold_fact(436, bruno, owns, guitar).
gold_fact(437, bruno, owns, guitar).
gold_fact(438, bruno, owns, guitar).
gold_fact(439, guitar, belongs_to, bruno).
gold_fact(440, pablo, reaches, ecuador).
gold_none(441).
gold_fact(442, sara, reaches, switzerland).
gold_fact(443, sara, reaches, norway).
gold_none(444).
gold_fact(445, jorge, reaches, ecuador).
gold_fact(446, gaia, lives_in, dublin).
gold_fact(447, gaia, lives_in, dublin).
gold_fact(448, gaia, works_in, oslo).
gold_fact(449, gaia, works_in, oslo).
gold_fact(450, gaia, visits, bern).
gold_fact(451, gaia, visits, bern).
gold_fact(452, gaia, visits, barcelona).
gold_fact(453, gaia, visits, barcelona).
gold_fact(454, gaia, visits, barcelona).
gold_fact(455, gaia, visits, bergen).
gold_fact(456, gaia, visits, bergen).
gold_fact(457, gaia, owns, drum).
gold_fact(458, gaia, owns, drum).
gold_fact(459, gaia, owns, drum).
gold_fact(460, drum, belongs_to, gaia).
gold_fact(461, gaia, owns, camera).
gold_fact(462, gaia, owns, camera).
gold_fact(463, gaia, owns, camera).
gold_fact(464, camera, belongs_to, gaia).
gold_fact(465, sofia, reaches, switzerland).
gold_fact(466, pedro, lives_in, barcelona).
gold_fact(467, pedro, lives_in, barcelona).
gold_fact(468, pedro, works_in, lyon).
gold_fact(469, pedro, works_in, lyon).
gold_fact(470, pedro, visits, oslo).
gold_fact(471, pedro, visits, oslo).
gold_fact(472, pedro, visits, paris).
gold_fact(473, pedro, visits, paris).
gold_fact(474, pedro, visits, roma).
gold_fact(475, pedro, visits, roma).
gold_fact(476, pedro, owns, tablet).
gold_fact(477, pedro, owns, tablet).
gold_fact(478, pedro, owns, tablet).
gold_fact(479, tablet, belongs_to, pedro).
gold_fact(480, pedro, owns, bicycle).
gold_fact(481, pedro, owns, bicycle).
gold_fact(482, pedro, owns, bicycle).
gold_fact(483, pedro, owns, bicycle).
gold_fact(484, bicycle, belongs_to, pedro).
gold_fact(485, carmen, reaches, peru).
gold_none(486).
gold_fact(487, ivan, reaches, italy).
gold_fact(488, elena, lives_in, roma).
gold_fact(489, elena, lives_in, roma).
gold_fact(490, elena, works_in, dublin).
gold_fact(491, elena, works_in, dublin).
gold_fact(492, elena, visits, milan).
gold_fact(493, elena, visits, milan).
gold_fact(494, elena, visits, lima).
gold_fact(495, elena, visits, lima).
gold_fact(496, elena, visits, bern).
gold_fact(497, elena, visits, bern).
gold_fact(498, elena, owns, bicycle).
gold_fact(499, elena, owns, bicycle).
gold_fact(500, elena, owns, bicycle).
gold_fact(501, bicycle, belongs_to, elena).
gold_fact(502, elena, owns, drum).
gold_fact(503, elena, owns, drum).
gold_fact(504, elena, owns, drum).
gold_fact(505, elena, owns, drum).
gold_fact(506, drum, belongs_to, elena).
gold_none(507).
gold_fact(508, marcos, reaches, spain).
gold_none(509).
gold_none(510).
gold_fact(511, teo, lives_in, milan).
gold_fact(512, teo, lives_in, milan).
gold_fact(513, teo, works_in, bern).
gold_fact(514, teo, works_in, bern).
gold_fact(515, teo, visits, quito).
gold_fact(516, teo, visits, quito).
gold_fact(517, teo, visits, dublin).
gold_fact(518, teo, visits, dublin).
gold_fact(519, teo, visits, madrid).
gold_fact(520, teo, visits, madrid).
gold_fact(521, teo, owns, lamp).
gold_fact(522, teo, owns, lamp).
gold_fact(523, teo, owns, lamp).
gold_fact(524, lamp, belongs_to, teo).
gold_fact(525, teo, owns, book).
gold_fact(526, teo, owns, book).
gold_fact(527, teo, owns, book).
gold_fact(528, teo, owns, book).
gold_fact(529, book, belongs_to, teo).
gold_none(530).
gold_fact(531, alba, lives_in, madrid).
gold_fact(532, alba, lives_in, madrid).
gold_fact(533, alba, works_in, paris).
gold_fact(534, alba, works_in, paris).
gold_fact(535, alba, visits, barcelona).
gold_fact(536, alba, visits, barcelona).
gold_fact(537, alba, visits, bergen).
gold_fact(538, alba, visits, bergen).
gold_fact(539, alba, visits, bergen).
gold_fact(540, alba, visits, lyon).
gold_fact(541, alba, visits, lyon).
gold_fact(542, alba, owns, book).
gold_fact(543, alba, owns, book).
gold_fact(544, alba, owns, book).
gold_fact(545, book, belongs_to, alba).
gold_fact(546, alba, owns, watch).
gold_fact(547, alba, owns, watch).
gold_fact(548, alba, owns, watch).
gold_fact(549, watch, belongs_to, alba).
gold_fact(550, ivan, lives_in, bergen).
gold_fact(551, ivan, lives_in, bergen).
gold_fact(552, ivan, works_in, milan).
gold_fact(553, ivan, works_in, milan).
gold_fact(554, ivan, visits, paris).
gold_fact(555, ivan, visits, paris).
gold_fact(556, ivan, visits, roma).
gold_fact(557, ivan, visits, roma).
gold_fact(558, ivan, visits, roma).
gold_fact(559, ivan, visits, quito).
gold_fact(560, ivan, visits, quito).
gold_fact(561, ivan, owns, guitar).
gold_fact(562, ivan, owns, guitar).
gold_fact(563, ivan, owns, guitar).
gold_fact(564, guitar, belongs_to, ivan).
gold_fact(565, ivan, owns, radio).
gold_fact(566, ivan, owns, radio).
gold_fact(567, ivan, owns, radio).
gold_fact(568, radio, belongs_to, ivan).
gold_fact(569, gaia, reaches, spain).
gold_fact(570, julia, reaches, spain).
gold_fact(571, sofia, lives_in, roma).
gold_fact(572, sofia, lives_in, roma).
gold_fact(573, sofia, works_in, dublin).
gold_fact(574, sofia, works_in, dublin).
gold_fact(575, sofia, visits, milan).
gold_fact(576, sofia, visits, milan).
gold_fact(577, sofia, visits, lima).
gold_fact(578, sofia, visits, lima).
gold_fact(579, sofia, visits, bern).
gold_fact(580, sofia, visits, bern).
gold_fact(581, sofia, owns, lamp).
gold_fact(582, sofia, owns, lamp).
gold_fact(583, sofia, owns, lamp).
gold_fact(584, lamp, belongs_to, sofia).
gold_fact(585, sofia, owns, book).
gold_fact(586, sofia, owns, book).
gold_fact(587, sofia, owns, book).
gold_fact(588, sofia, owns, book).
gold_fact(589, book, belongs_to, sofia).
gold_fact(590, julia, lives_in, madrid).
gold_fact(591, julia, lives_in, madrid).
gold_fact(592, julia, works_in, paris).
gold_fact(593, julia, works_in, paris).
gold_fact(594, julia, visits, barcelona).
gold_fact(595, julia, visits, barcelona).
gold_fact(596, julia, visits, bergen).
gold_fact(597, julia, visits, bergen).
gold_fact(598, julia, visits, lyon).
gold_fact(599, julia, visits, lyon).
gold_fact(600, julia, owns, tablet).
gold_fact(601, julia, owns, tablet).
gold_fact(602, julia, owns, tablet).
gold_fact(603, tablet, belongs_to, julia).
gold_fact(604, julia, owns, bicycle).
gold_fact(605, julia, owns, bicycle).
gold_fact(606, julia, owns, bicycle).
gold_fact(607, julia, owns, bicycle).
gold_fact(608, bicycle, belongs_to, julia).
gold_fact(609, eric, reaches, france).
gold_none(610).
gold_none(611).
gold_fact(612, vera, reaches, norway).
gold_fact(613, carmen, lives_in, paris).
gold_fact(614, carmen, lives_in, paris).
gold_fact(615, carmen, works_in, quito).
gold_fact(616, carmen, works_in, quito).
gold_fact(617, carmen, visits, lyon).
gold_fact(618, carmen, visits, lyon).
gold_fact(619, carmen, visits, milan).
gold_fact(620, carmen, visits, milan).
gold_fact(621, carmen, visits, milan).
gold_fact(622, carmen, visits, lima).
gold_fact(623, carmen, visits, lima).
gold_fact(624, carmen, owns, camera).
gold_fact(625, carmen, owns, camera).
gold_fact(626, carmen, owns, camera).
gold_fact(627, camera, belongs_to, carmen).
gold_fact(628, carmen, owns, chess).
gold_fact(629, carmen, owns, chess).
gold_fact(630, carmen, owns, chess).
gold_fact(631, chess, belongs_to, carmen).
gold_fact(632, eric, reaches, norway).
gold_fact(633, nora, reaches, peru).
gold_fact(634, mia, lives_in, roma).
gold_fact(635, mia, lives_in, roma).
gold_fact(636, mia, works_in, dublin).
gold_fact(637, mia, works_in, dublin).
gold_fact(638, mia, visits, milan).
gold_fact(639, mia, visits, milan).
gold_fact(640, mia, visits, lima).
gold_fact(641, mia, visits, lima).
gold_fact(642, mia, visits, bern).
gold_fact(643, mia, visits, bern).
gold_fact(644, mia, owns, bicycle).
gold_fact(645, mia, owns, bicycle).
gold_fact(646, mia, owns, bicycle).
gold_fact(647, bicycle, belongs_to, mia).
gold_fact(648, mia, owns, drum).
gold_fact(649, mia, owns, drum).
gold_fact(650, mia, owns, drum).
gold_fact(651, mia, owns, drum).
gold_fact(652, drum, belongs_to, mia).
gold_fact(653, ines, reaches, switzerland).
gold_fact(654, mia, reaches, switzerland).
gold_none(655).
gold_fact(656, lucia, reaches, peru).
